Repository iguazio/dashboard-controls, pull requests merged in 2018-12, with the labels that each got.

#372 Impl [Nuclio] Add support to function templates with params
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
Labels: enhancement

#373 Create a new dist version 0.4.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#369 Fixed import function bug
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
Labels: bug

#370 Moved timeout block to demo mode
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#374 IG-2031 [Nuclio] Add Export button to projects actions bar
  src/nuclio/projects/projects.component.js
Labels: enhancement

#375 Fix [Nuclio] "Discard changes?" on screen leave falsely displayed
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#376 Create a new dist version 0.4.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#377 Fix [Nuclio] Code: Event Pane: breaks when on empty response body
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#378 Create a new dist version 0.4.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#381 Create a new dist version 0.4.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#384 Create a new dist version 0.4.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#385 IG-2020 [Tenants] New tenant number input issues
  src/igz_controls/components/number-input/number-input.component.js
Labels: bug

#386 IG-2035 [Nuclio] Remove Pypy runtime entirely
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.spec.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
Labels: enhancement

#388 Fix [Projects] Checkbox is still checked after failed deletion
  src/igz_controls/less/dialogs.less
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.tpl.html
  src/nuclio/projects/projects.component.js
  src/nuclio/projects/projects.tpl.html
Labels: bug

#387 IG-2040 [Nuclio] Last env var is removed on removing another
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
Labels: bug

#389 Create a new dist version 0.4.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#392 Fix [Nuclio] Code: Test pane: Format JSON response misbehaves
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#391 IG-2041 [Nuclio] White background in description cell on hover
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
Labels: bug

#393 Create a new dist version 0.4.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#394 IG-2047 [Nuclio] Configuration: move logging level to prod
  src/nuclio/common/services/export.service.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#395 Fix [Nuclio] Code: Test pane: fail when response is object
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#398 Impl [General] Separate drilldown table cell style
  src/igz_controls/less/table.less
Labels: enhancement

#397 IG-2042 [Nuclio] Sorting functions by status issue
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: bug

#399 Create a new dist version 0.4.8
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#401 Impl [Nuclio] Display "Scaled to zero" in function "Status" column
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
Labels: enhancement

#400 IG-2049 [Nuclio] Test pane>Request>File: breaks Text/JSON
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#402 Fix [Nuclio] Invocation URL is N/A for deployed functions
  src/nuclio/projects/project/functions/functions.component.js
Labels: bug

#403 Create a new dist version 0.4.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#405 IG-2050 [Nuclio] Triggers: add "Clear" to Cron schedule
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#404 IG-2044 [Data-Access Policy] Shift to async transactions
  src/igz_controls/components/action-checkbox-all/action-checkbox-all.component.js
Labels: bug

#406 Create a new dist version 0.4.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#408 Create a new dist version 0.4.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#410 Create a new dist version 0.4.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#411 Impl [Nuclio] Function template params: order by `order` property
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
Labels: bug, enhancement

#412 Create a new dist version 0.4.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
