Repository iguazio/dashboard-controls, pull requests merged in 2018-08, with the labels that each got.

#214 Fix [Nuclio] Failed unit-tests in project creation/edition
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.spec.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.spec.js
Labels: bug

#215 Impl [General] Add package-lock.json to .gitignore
  .gitignore
Labels: enhancement

#210 IG-1734 [Build] Upgrade to latest Node+npm
  .bowerrc
  bower.json
  build.config.js
  package.json
Labels: enhancement

#216 IG-1935 [Nuclio] Change main menu item to "Functions"
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#213 IG-1870 [Storage] Create new storage console issue
  src/igz_controls/components/number-input/number-input.component.js
Labels: bug

#217 IG-1932 [Nuclio] Add tooltips to collapse all/expand all
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.tpl.html
Labels: enhancement

#219 Create a new dist version 0.1.9
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#221 IG-1941 [Nuclio] Visual bug in Test pane
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: bug

#225 Fix [Nuclio] `spec.disabled` was used instead of `spec.disable`
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#229 Create a new dist version 0.1.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#218 IG-1929 [Nuclio][Create Function] Refactor "New function from template" screen
  src/igz_controls/components/pagination/pagination.component.js
  src/igz_controls/components/pagination/pagination.component.spec.js
  src/igz_controls/components/pagination/pagination.component.tpl.html
  src/igz_controls/components/pagination/pagination.controller.js
  src/igz_controls/components/pagination/pagination.less
  src/igz_controls/components/pagination/pagination.service.js
  src/igz_controls/services/local-storage.service.js
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.less
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.tpl.html
Labels: enhancement

#230 Create a new dist version 0.1.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#212 IG-1881 [Nuclio] Add left navigation menu
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/less/general-rules.less
  src/nuclio/common/less/palette.less
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#231 Create a new dist version 0.1.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#232 Impl [Containers] Disallow upper-case letters in container names
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#233 Create a new dist version 0.1.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#238 IG-1947 [Nuclio] Make "Templates" the first and default option
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/create-function/create-function.tpl.html
Labels: enhancement

#240 Fix [Nuclio] No error message on failed deploy, infinite spinner
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#241 Create a new dist version 0.1.15
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#242 Fixed UT to the task IG-1947
  src/nuclio/projects/project/functions/create-function/create-function.component.spec.js
Labels: bug

#234 IG-1933 [General] Add mechanism to set color scheme
  package.json
  src/igz_controls/components/action-checkbox-all/action-checkbox-all.less
  src/igz_controls/components/action-checkbox/action-checkbox.less
  src/igz_controls/components/action-menu/action-menu.less
  src/igz_controls/components/action-panel/action-panel.less
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/components/info-page/info-page-actions-bar/info-page-actions-bar.less
  src/igz_controls/components/info-page/info-page-content/info-page-content.less
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.less
  src/igz_controls/components/number-input/number-input.less
  src/igz_controls/components/search-input/search-input.less
  src/igz_controls/components/slider-input-block/slider-input-block.less
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/less/buttons.less
  src/igz_controls/less/dialogs.less
  src/igz_controls/less/general-rules.less
  src/igz_controls/less/helpers.less
  src/igz_controls/less/icons.less
  src/igz_controls/less/inputs.less
  src/igz_controls/less/palette.less
  src/igz_controls/less/table.less
  src/igz_controls/less/tooltips.less
  src/igz_controls/less/variables.less
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.less
  src/nuclio/common/components/collapsing-row/collapsing-row.less
  src/nuclio/common/components/deploy-log/deploy-log.less
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/monaco/monaco.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/common/components/nuclio-search-input/search-input.less
  src/nuclio/common/less/buttons.less
  src/nuclio/common/less/dialogs.less
  src/nuclio/common/less/general-rules.less
  src/nuclio/common/less/palette.less
  src/nuclio/common/less/tooltips.less
  src/nuclio/projects/project/functions/create-function/create-function.less
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.less
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.less
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/projects/project/functions/function-collapsing-row/function-version-row/function-version-row.less
  src/nuclio/projects/project/functions/function.less
  src/nuclio/projects/project/functions/version/function-event-dialog/function-event-dialog.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.less
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build-dialog/version-configuration-build-dialog.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.less
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.less
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.less
  src/nuclio/projects/project/functions/version/version.less
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.less
  src/nuclio/projects/projects.less
Labels: enhancement

#243 Create a new dist version 0.2.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#245 IG-1955 [Nuclio] Source code changes not deployed
  src/nuclio/common/components/monaco/monaco.component.js
  src/nuclio/common/components/monaco/monaco.tpl.html
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
Labels: bug

#246 Create a new dist version 0.2.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#249 Create a new dist version 0.2.2
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#250 IG-1954 [Storage Pools] New storage console error
  src/igz_controls/components/number-input/number-input.component.js
Labels: bug

#251 IG-1962 [Nuclio] Create new function import broken
  src/nuclio/common/components/monaco/monaco.component.js
  src/nuclio/projects/project/functions/create-function/function-import/function-import.component.js
  src/nuclio/projects/project/functions/create-function/function-import/function-import.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: bug
