Repository iguazio/dashboard-controls, pull requests merged in 2018-09, with the labels that each got.

#255 IG-1953 [Nuclio] Add "New function" to Projects screen
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/less/buttons.less
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/create-function/create-function.tpl.html
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.spec.js
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.less
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.less
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/projects/project/functions/create-function/function-import/function-import.component.js
  src/nuclio/projects/project/functions/create-function/function-import/function-import.less
  src/nuclio/projects/project/functions/create-function/function-import/function-import.tpl.html
  src/nuclio/projects/projects.component.js
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#256 Create a new dist version 0.2.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#253 IG-1963 [Home] Implement new Home screen
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/nuclio/projects/project/functions/create-function/create-function.component.js
Labels: enhancement

#259 IG-1972 [Nuclio] First project not selected in new function
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/create-function/function-import/function-import.component.js
Labels: bug

#260 IG-1974 [Services] Change Services icon on the left menu
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#261 Create a new dist version 0.2.4
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#264 Fix response body for "Test events"
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#266 IG-1956 [General] Unit-tests runner newline
  package.json
  src/igz_controls/components/slider-input-block/slider-input-block.component.spec.js
  tests/unit/karma.config.js
Labels: bug, enhancement

#254 Final implementation of new color scheme
  src/igz_controls/components/action-checkbox-all/action-checkbox-all.less
  src/igz_controls/components/action-checkbox/action-checkbox.less
  src/igz_controls/components/action-menu/action-menu.less
  src/igz_controls/components/action-panel/action-panel.less
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/components/elastic-input-field/elastic-input-field.less
  src/igz_controls/components/info-page/info-page-actions-bar/info-page-actions-bar.less
  src/igz_controls/components/info-page/info-page-content/info-page-content.less
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.less
  src/igz_controls/components/number-input/number-input.less
  src/igz_controls/components/pagination/pagination.less
  src/igz_controls/components/search-input/search-input.less
  src/igz_controls/components/slider-input-block/slider-input-block.less
  src/igz_controls/components/sort-dropdown/sort-dropdown.less
  src/igz_controls/components/splash-screen/splash-screen.less
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/less/buttons.less
  src/igz_controls/less/dialogs.less
  src/igz_controls/less/general-rules.less
  src/igz_controls/less/helpers.less
  src/igz_controls/less/icons.less
  src/igz_controls/less/inputs.less
  src/igz_controls/less/loader-spinner.less
  src/igz_controls/less/table.less
  src/igz_controls/less/tooltips.less
  src/igz_controls/less/variables.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
Labels: enhancement

#274 Create a new dist version v0.2.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#263 IG-1976 [Create Function] Move Create Function screen to common folder.
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.component.spec.js
  src/nuclio/common/screens/create-function/create-function.less
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.spec.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.less
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.less
  src/nuclio/common/screens/create-function/function-import/function-import.tpl.html
Labels: Cleanup

#270 IG-1967 [General] Upgrade to AngularJs v1.7
  package.json
  src/iguazio.dashboard-controls.config.js
  src/igz_controls/components/action-item/action-item.component.js
  src/igz_controls/services/dialogs.service.js
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.spec.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-version-row/function-version-row.component.js
Labels: enhancement

#271 [General] Upgrade to latest ui-router and ng-scrollbars
  build.config.js
  package.json
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.spec.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#273 [General] Upgrade to latest ui-bootstrap
  build.config.js
  package.json
  src/iguazio.dashboard-controls.config.js
  src/igz_controls/components/action-item/action-item-more/action-item-more.tpl.html
  src/igz_controls/components/action-item/action-item-refresh/action-item-refresh.tpl.html
  src/igz_controls/components/action-item/action-item.tpl.html
  src/igz_controls/components/actions-panes/actions-panes.tpl.html
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
  src/igz_controls/components/elastic-input-field/elastic-input-field.tpl.html
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.less
  src/igz_controls/components/pagination/pagination.component.tpl.html
  src/igz_controls/components/sort-dropdown/sort-dropdown.tpl.html
  src/igz_controls/services/dialogs.service.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/projects/project/functions/version/version.tpl.html
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#275 Create a new dist version 0.3.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement
