Repository iguazio/dashboard-controls, pull requests merged in 2018-11, with the labels that each got.

#330 Added horizontal test pane splitter
  src/nuclio/common/components/navigation-tabs/navigation-tabs.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#331 Create a new dist version 0.3.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#333 Fix [Nuclio] Status tab: invocation URL N/A for deployed funcion
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#334 Create a new dist version 0.3.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#336 IG-1996 [General] Action bar is empty for some screens
  src/igz_controls/components/action-item/action-item.component.js
Labels: bug

#337 IG-2008 [Nuclio] Configuration Build section Readiness timeout input issues
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: bug

#338 IG-2009 [Nuclio] Configuration Build section console issue
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: bug

#339 IG-2002 [Nuclio] Image/Archive Entry Type scroll doesn't work
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
Labels: bug

#335 IG-2005 [Tenants] Add Quota and Quota Thresholds on create
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#340 Create a new dist version 0.3.14
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#341 IG-2011 Impl [Users] Backup User add specific warnings
  src/igz_controls/components/action-panel/action-panel.component.js
Labels: enhancement

#343 IG-2017 [Nuclio] Add "Export" button to project screen
  src/iguazio.dashboard-controls.module.js
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/igz_controls/services/angular-yamljs.service.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#344 Create a new dist version 0.3.15
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#345 KubeCon18 - Target CPU (add tooltip)
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#347 [KubeCon 18] Create function – move button to the upper section near the import button
  src/nuclio/common/screens/create-function/function-import/function-import.less
  src/nuclio/common/screens/create-function/function-import/function-import.tpl.html
Labels: enhancement

#348 Impl [General] Add "test-id" attribute to dialog buttons
  src/igz_controls/services/dialogs.service.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.tpl.html
  src/nuclio/projects/new-project-dialog/new-project-dialog.tpl.html
Labels: enhancement

#346 IG-2016 [Nuclio] Code tab: Add "Change text size" button
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/nuclio/common/components/monaco/monaco.component.js
  src/nuclio/common/components/monaco/monaco.less
  src/nuclio/common/components/monaco/monaco.tpl.html
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.component.js
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.component.spec.js
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.less
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.tpl.html
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#349 Create a new dist version 0.3.16
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#350 Impl [Nuclio] Configuration: Volumes: add Secret and Config Map
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.tpl.html
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.tpl.html
Labels: Cleanup, enhancement

#351 Create a new dist version v0.3.17
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#352 Added possibility to export project(s)
  src/nuclio/common/services/export.service.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.spec.js
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.spec.js
  src/nuclio/projects/projects.component.js
  src/nuclio/projects/projects.component.spec.js
  src/nuclio/projects/projects.less
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#353 Create a new dist version 0.3.18
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#354 KubeCon18 - View YAML of function config
  src/nuclio/common/components/function-config-dialog/function-config-dialog.component.js
  src/nuclio/common/components/function-config-dialog/function-config-dialog.less
  src/nuclio/common/components/function-config-dialog/function-config-dialog.tpl.html
  src/nuclio/common/services/export.service.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#357 Create a new dist version 0.3.19
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#358 Added more space for build commands in configuration
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#356 Function templates allow rendering, be taken from a Github repo
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
Labels: enhancement

#359 Create a new dist version 0.3.20
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#361 Revert [Nuclio] Add support to function templates with params
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
Labels: revert

#362 Create a new dist version 0.3.21
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: revert

#363 When creating a function, pressing "enter" should click the "create" button
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
Labels: enhancement

#365 KubeCon 18 - Projects (and probably functions) should be sorted by default
  src/nuclio/projects/projects.component.js
Labels: enhancement

#366 Create a new dist version 0.3.22
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#368 Create a new dist version 0.3.23
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
