Repository iguazio/dashboard-controls, pull requests merged in 2018-07, with the labels that each got.

#179 Create a new dist version 0.0.63
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#176 IG-1742 [Nuclio] Implement Nuclio API for Iguazio
  package-lock.json
  src/iguazio.dashboard-controls.route.js
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/services/nuclio-client.service.js
  src/nuclio/common/services/nuclio-event-data.servie.js
  src/nuclio/common/services/nuclio-functions-data.service.js
  src/nuclio/common/services/nuclio-projects-data.service.js
  src/nuclio/common/services/nuclio-version-data.service.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.js
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/create-function/create-function.tpl.html
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/project/functions/version/function-event-dialog/function-event-dialog.component.js
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/project/functions/version/version.tpl.html
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.component.js
  src/nuclio/projects/projects.component.js
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#180 Create a new dist version 0.1.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#181 Removed redundant services injection
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#182 Create a new dist version 0.1.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#183 Cleanup [Nuclio] Remove unnecessary injections
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/monaco/monaco.component.js
  src/nuclio/common/services/nuclio-header.service.js
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/function/ncl-function.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.component.js
  src/nuclio/projects/project/functions/version/version-trigger/version-trigger.component.js
  src/nuclio/projects/projects.component.js
Labels: Cleanup

#184 Fix [Nuclio] Path of function event not saved properly
  src/nuclio/projects/project/functions/version/function-event-dialog/function-event-dialog.component.js
  src/nuclio/projects/project/functions/version/function-event-dialog/function-event-dialog.tpl.html
Labels: bug

#187 Impl [Nuclio] Change Ruby runtime default source code
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.spec.js
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
Labels: enhancement

#188 Create a new dist version 0.1.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#191 Create a new dist version 0.1.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#193 Impl [Nuclio] Revive missing code from PR #190
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.js
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/projects.tpl.html
Labels: Cleanup, bug, enhancement

#194 Create a new dist version 0.1.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#195 Fix [Nuclio] Various issues when integrating with Iguazio
  .babelrc
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/project/functions/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
Labels: bug, enhancement

#196 Revert [General] Remove ignore entry in .babelrc
  .babelrc
Labels: Cleanup

#197 Create a new dist version 0.1.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#189 use js-base64 instead of atob/btoa for utf-8 characters
  bower.json
  build.config.js
  src/iguazio.dashboard-controls.config.js
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
Labels: enhancement

#198 IG-1913 , IG-1915
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.less
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#192 IG-1914 [Nuclio] Broken screen on nav to non-existing project
  src/nuclio/projects/project/functions/functions.component.js
Labels: bug

#200 IG-1922 [Nuclio] Remove "Num Container Workers" field
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#199 IG-1921 [General] Dialog descriptions redesign
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/less/dialogs.less
Labels: enhancement

#201 IG-1916 [Nuclio] Add "Num Workers" to v3io data binding
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.component.js
Labels: enhancement

#175 IG-1786 [Nuclio] Implement "Test" pane
  build.config.js
  package.json
  src/iguazio.dashboard-controls.module.js
  src/igz_controls/components/elastic-input-field/elastic-input-field.component.js
  src/igz_controls/components/elastic-input-field/elastic-input-field.component.spec.js
  src/igz_controls/components/elastic-input-field/elastic-input-field.less
  src/igz_controls/components/elastic-input-field/elastic-input-field.tpl.html
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/buttons.less
  src/igz_controls/less/icons.less
  src/igz_controls/services/convertor-service.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/components/monaco/monaco.component.js
  src/nuclio/common/components/monaco/monaco.less
  src/nuclio/common/components/monaco/monaco.tpl.html
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
  src/nuclio/common/less/buttons.less
  src/nuclio/common/less/palette.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/project/functions/version/version.less
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: enhancement

#203 IG-1924 [General] Remove border when no drill-down
  src/igz_controls/less/table.less
Labels: enhancement

#204 Fixed comments on #175
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.tpl.html
Labels: bug

#206 Create a new dist version 0.1.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#207 Fix [Nuclio] Function creation/deletion not working + more
  dist/images/oops.png
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.js
  src/nuclio/projects/project/functions/create-function/create-function.component.js
  src/nuclio/projects/project/functions/create-function/function-from-template/function-from-template.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
Labels: bug, enhancement

#208 Create a new dist version 0.1.8
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#211 Urgent fixes
  src/igz_controls/services/convertor-service.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: bug
