Repository iguazio/dashboard-controls, pull requests merged in 2018-10, with the labels that each got.

#276 IG-1991 [Nuclio] Add collapse/expand button to test pane
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.component.js
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: enhancement

#277 Create a new dist version 0.3.1
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#279 fixed ui-router transition issue
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#280 Create a new dist version 0.3.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#281 IG-1986 [Nuclio] Field overflow on Image/Archive Entry Type
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: bug

#282 Fixed issue with 'toggle test pane' button and 'test' button.
  src/nuclio/common/components/navigation-tabs/navigation-tabs.component.js
  src/nuclio/common/components/navigation-tabs/navigation-tabs.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#283 Configuration/Build
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#285 Added new fields for triggers (p1)
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#284 Configuration/Build: Java specific
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.less
Labels: enhancement

#287 Triggers/All: Add "Worker allocator name"
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#288 Create a new dist version 0.3.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#290 Configuration/Environment: Support configmap / secret
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
Labels: enhancement

#292 fixed issue with collapse/expand test pane
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
Labels: bug

#291 Configuration/Basic Settings: Show timeout
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#293 Configuration/Runtime attributes: Support java/shell
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.component.js
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.tpl.html
Labels: enhancement

#294 Added MQTT trigger
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version.less
Labels: enhancement

#295 Trello cron add fields
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/projects/project/functions/version/version.less
Labels: enhancement

#296 Create a new dist version 0.3.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#297 Code: Add "GitHub" Code Entry Type
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#298 Code: Add "Work Dir" to "Archive" code entry type
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#302 Create a new dist version 0.3.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#303 Added draggable splitter to request/response sections
  package.json
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: enhancement

#305 Configuration/Build: Java specific
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#306 WorkerAllocatorName should not be in Volumes
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: bug

#307 Deploy fails with empty build commands
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: bug

#310 Wrapped checkbox on Build tab fixed.
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
Labels: bug

#312 sasl-enable-fixes
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: bug

#313 UI doesn't convert Worker Availability Timeout (seconds) to millieseconds, as expected by the backend
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#311 Configuration/Build: Add "Readiness timeout (seconds)"
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#304 Added "Log Level" drop-down menu in event pane
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.tpl.html
Labels: enhancement

#316 Create a new dist version 0.3.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#317 Fix [Nuclio] Scrollbars keep scrolling to bottom on deploy+exit
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#321 Create a new dist version 0.3.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#322 Fix [Nuclio] Code entry attributes are falsely sent
  src/iguazio.dashboard-controls.config.js
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: bug

#323 Create a new dist version 0.3.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#315 Invocation port changes, it is not reflected in status pane
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#327 Fixed cropping of code entry section
  src/nuclio/projects/project/functions/version/version-code/version-code.less
Labels: bug

#328 Integrated Angular plugin for Cron scheduler
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement
