Repository iguazio/dashboard-controls, pull requests merged in 2019-05, with the labels that each got.

#564 Impl [Nuclio] Make placeholder text more consistent
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/projects/new-project-dialog/new-project-dialog.tpl.html
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/projects/project/functions/version/function-event-dialog/function-event-dialog.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build-dialog/version-configuration-build-dialog.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
Labels: enhancement

#565 Create a new dist version 0.8.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#567 Fix [Nuclio] Function list: Filter: Incorrect placeholder text
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: bug

#568 Impl [Build] Remove "sync-exec" dependency (unused, security risk)
  package.json
Labels: enhancement

#566 IG-2247 [Nuclio] Template parameters dialog number input issue
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
Labels: bug

#569 IG-2251 [Nuclio] HTTP Trigger: removing an ingress collapses the row
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: bug

#570 Create a new dist version 0.8.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#571 Impl [General] Reduce clickable area of "Create new X..." buttons
  src/nuclio/common/less/general-rules.less
Labels: enhancement

#572 Impl [General] igzMoreInfo: Add support for HTML tooltips
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
  src/igz_controls/less/general-rules.less
  src/igz_controls/less/tooltips.less
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#573 Create a new dist version 0.8.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#574 IG-2252 [Nuclio] Volumes: Add PVC volume type
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#575 IG-2255 [Nuclio] Add "Service Account" in "Basic Settings"
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#576 Create a new dist version 0.8.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#577 IG-2256 [Clusters] Add "Type" column
  src/igz_controls/less/igz-grid.less
Labels: enhancement

#578 Create a new dist version 0.8.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#580 Impl [Nuclio] Triggers: HTTP: Ingress: Auto-populate host
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#581 Create a new dist version 0.8.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#583 IG-2266 [Nuclio] Deploy is enabled when value is invalid
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: bug

#582 IG-2271 [Pipelines] Add Pipelines icon
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#584 Create a new dist version 0.8.8
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#585 Cleanup [Nuclio] Configuration: Resources: GPU Request leftovers
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: Cleanup

#587 Impl [Nuclio] Code: Rename label "work dir" to "working directory"
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#589 IG-2276 [Nuclio] Configuration: Remove "Data Bindings" pane
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.tpl.html
Labels: enhancement

#588 IG-2265 [Browse] Allow leading/trailing spaces in folder names
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/igz_controls/directives/input-only-valid-characters.js
  src/igz_controls/services/dialogs.service.js
Labels: enhancement

#590 Create a new dist version 0.8.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#586 IG-2273 [Nuclio] Configurations Build action menu button clickable area is shifted
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: bug

#592 Fix [Nuclio] Config:Resources:Memory: Change unit `'K'` to `'k'`
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
Labels: bug

#593 Create a new dist version 0.8.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#594 Fix [Nuclio] Latest changes not taken on Deploy
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
Labels: bug

#595 Create a new dist version 0.8.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#596 IG-2282 [Nuclio] Build: Remove "No internet access" checkbox
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#597 IG-2278 [Nuclio] Function list: filter not working
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: bug

#598 IG-2280 [Nuclio] Triggers:HTTP:Ingress:Create: Default path to '/'
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: enhancement

#599 Create a new dist version 0.8.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
