Repository iguazio/dashboard-controls, pull requests merged in 2019-11, with the labels that each got.

#774 [General] Increase the spacing bellow validating input
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
Labels: enhancement

#776 Fix [General] igzValidatingInput: debounce stopped working
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#777 Create a new dist version
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#775 [General] Monaco editor should keep editing after close confirm dialog
  src/igz_controls/less/buttons.less
  src/igz_controls/services/dialogs.service.js
Labels: enhancement

#772 [Nuclio] Stop using external_ip_addresses end-point
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.component.js
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.spec.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.tpl.html
Labels: enhancement

#778 Create a new dist version 0.11.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#779 [Nuclio] Code entry type tooltips are partially hidden
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
Labels: bug

#781 [Browse] Attributes: console error on apply edit
  src/igz_controls/services/prevent-dropdown-cut-off.service.js
Labels: bug

#783 Fix [General] igzValidatingInputField: failed unit test
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
Labels: bug

#782 [General] igzActionMenu: align no-icon options
  src/igz_controls/components/action-item/action-item.component.js
  src/igz_controls/components/action-item/action-item.tpl.html
  src/igz_controls/components/action-menu/action-menu.less
  src/igz_controls/components/action-menu/action-menu.tpl.html
Labels: bug

#784 Create a new dist version 0.11.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#785 [Nuclio] Functions sorting doesn't work
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
Labels: bug

#786 [Nuclio] Projects: expand not working on init
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
Labels: bug

#787 [Nuclio] Functions: charts broken after function deletion
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
Labels: bug

#788 [Nuclio] Projects: Add each project's functions sorting by Status, Replicas
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
Labels: enhancement

#789 [Nuclio] Projects: Hide expand icon for empty projects
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.component.js
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.component.spec.js
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.tpl.html
Labels: enhancement

#790 [Nuclio] Versions columns display incorrect on Projects screen for small browser resolution
  src/i18n/en/functions.json
  src/igz_controls/components/info-page/info-page-content/info-page-content.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.tpl.html
  src/nuclio/projects/projects-functions-view/projects-functions-view.less
  src/nuclio/projects/projects-functions-view/projects-functions-view.tpl.html
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.tpl.html
Labels: bug

#791 [Nuclio] Invocations column changes
  src/i18n/en/functions.json
  src/igz_controls/components/size/size.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/projects/projects-functions-view/projects-functions-view.tpl.html
Labels: enhancement

#792 [Data Clusters] Add “Switch to online maintenance” action
  src/i18n/en/common.json
Labels: Cleanup

#793 Create a new dist version 0.11.2
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#794 Impl [Nuclio] Triggers: add tooltips to Class drop-down options
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#795 Impl [Geenral] igzDefaultDropdown: add ellipsis to options
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
Labels: enhancement

#796 Create a new dist version 0.11.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#797 Impl [Nuclio] Triggers: HTTP: Ingresses: Rename and add *
  src/i18n/en/functions.json
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#798 Create a new dist version 0.11.4
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#799 [Nuclio] Projects: no initial sort defined
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.tpl.html
Labels: bug

#801 [Nuclio] Make project column sortable
  src/igz_controls/components/sort-dropdown/sort-dropdown.component.js
  src/igz_controls/components/sort-dropdown/sort-dropdown.component.spec.js
  src/igz_controls/components/sort-dropdown/sort-dropdown.tpl.html
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.spec.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.tpl.html
Labels: enhancement

#800 [Browse] View HTML files in UI
  src/igz_controls/less/dialogs.less
  src/igz_controls/services/dialogs.service.js
Labels: enhancement

#802 [Services] Use `name` instead of `display_name`
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: enhancement

#803 Create a new dist version 0.11.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#804 Impl [Nuclio] Functions: add `test-id` attributes to data cells
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
Labels: enhancement

#805 Create a new dist version 0.11.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#806 [Browse] HTML viewer displays incorrect for small browser resolution
  src/igz_controls/less/dialogs.less
Labels: bug
