Repository iguazio/dashboard-controls, pull requests merged in 2019-12, with the labels that each got.

#808 Impl [DialogService] Use <iframe> in sandbox mode for security
  src/igz_controls/services/dialogs.service.js
Labels: enhancement

#807 [Nuclio] Error occurs after edit project dialog close by Esc
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.spec.js
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.component.js
  src/nuclio/projects/project-collapsing-row/project-collapsing-row.component.spec.js
  src/nuclio/projects/projects-functions-view/projects-functions-view.component.spec.js
Labels: bug

#809 Fix [Nuclio] Invocation URL displayed with port number 0
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#810 Create a new dist version 0.11.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#750 UI field validation
  src/i18n/en/functions.json
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/services/validating-patterns.service.js
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
Labels: enhancement

#812 Create a new dist version 0.11.8
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#811 [Nuclio] Build: display error instead of log entries
  src/nuclio/common/components/deploy-log/deploy-log.component.js
  src/nuclio/common/components/deploy-log/deploy-log.tpl.html
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: enhancement

#813 Create a new dist version 0.11.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#814 Impl [General] Improve alignment of validation rule icon to text
  src/igz_controls/components/validating-input-field/validating-input-field.less
Labels: enhancement

#815 [Services] Wizard: name is always invalid after type selected
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#816 Create a new dist version 0.11.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#817 [Services] Set max name length to 53
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: enhancement

#818 Create a new dist version 0.11.11
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#819 Impl [Nuclio] Build: display error instead of log entries
  src/nuclio/common/components/deploy-log/deploy-log.component.js
  src/nuclio/common/components/deploy-log/deploy-log.tpl.html
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: enhancement

#821 Create a new dist version 0.9.42
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#822 [Nuclio] Import: Add error message on error parsing YAML
  src/i18n/en/common.json
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
Labels: enhancement

#823 Create a new dist version 0.12.0
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#824 [Services] Presto>Advanced: Add config-map key validation
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: enhancement

#825 Create a new dist version 0.12.1
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#827 Create a new dist version 0.13.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#829 Fix [Nuclio] Status: No invocation URL when scaled-to-zero
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
Labels: bug

#830 Create a new dist version 0.13.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#832 [General] igzValidatingInputField: text overlaps validation icon
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: bug

#831 [Services] Presto: Validation pop-up not open on icon click
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: bug

#833 Create a new dist version 0.13.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#835 Create a new dist version 0.14.0
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#836 Impl [Nuclio] Function>Code>Archive>URL: Reword placeholder
  src/nuclio/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#837 Fix [Nuclio] Export all: Empty projects are not exported
  src/nuclio/common/services/export.service.js
Labels: bug

#838 Create a new dist version 0.14.1
  dist/js/iguazio.dashboard-controls.js
  package.json
Labels: bug, enhancement

#839 Impl [Nuclio] Accommodate to new default ingress host template
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#840 Create a new dist version 0.14.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#841 [API Gateways] Add new "API Gateways" tab under project
  src/i18n/en/functions.json
  src/igz_controls/components/search-input/search-helper.service.js
  src/igz_controls/components/search-input/search-input.component.js
  src/igz_controls/components/search-input/show-hide-search-item.directive.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/services/nuclio-header.service.js
  src/nuclio/functions/functions.component.js
Labels: enhancement

#842 Create a new dist version 0.15.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#846 Impl [General] igzActionItem: support `.tooltip` property
  src/igz_controls/components/action-item/action-item.component.js
  src/igz_controls/components/action-item/action-item.tpl.html
  src/igz_controls/components/action-menu/action-menu.less
Labels: enhancement

#844 [Services] Jupyter: add PVCs
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
Labels: enhancement

#845 [Nuclio] UI field unique validation fails
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: bug

#843 Functions: Invocation URL: add copy to clipboard
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/functions/version/version-monitoring/version-monitoring.component.js
  src/nuclio/functions/version/version-monitoring/version-monitoring.less
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
Labels: enhancement

#847 Create a new dist version 0.15.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
