Repository iguazio/dashboard-controls, pull requests merged in 2019-08, with the labels that each got.

#675 [Nuclio] Use project name instead of display name
  src/i18n/en/functions.json
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/common/services/export.service.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.spec.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.tpl.html
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.spec.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.tpl.html
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.spec.js
  src/nuclio/projects/projects-table-row/projects-table-row.tpl.html
  src/nuclio/projects/projects.component.js
  src/nuclio/projects/projects.component.spec.js
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#682 Create a new dist version 0.9.13
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#683 [Nuclio] Wrong clickable area for volume creation
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.less
Labels: bug

#684 [Browse] Table view: add column resize and auto-fit
  src/igz_controls/directives/resizable-row-cells.directive.js
  src/igz_controls/directives/resizable-table-column.directive.js
Labels: enhancement

#685 Create a new dist version 0.9.14
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#687 Fix [Pagination] Falsely sends additional request on empty list
  src/igz_controls/components/pagination/pagination.controller.js
Labels: bug

#688 Create a new dist version 0.9.15
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#670 [General] Default drop-down: add autocomplete feature
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/igz_controls/components/default-dropdown/default-dropdown.component.spec.js
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
Labels: enhancement

#690 [Services] Add "Public" icon; [Browse] Update timestamp attribute-type icon
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#689 [Nuclio] Disable “Labels” for deployed functions
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/less/general-rules.less
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#691 Create a new dist version 0.9.16
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#692 [Browse] Add keyboard shortcuts to "Create new folder"
  src/igz_controls/services/dialogs.service.js
Labels: enhancement

#693 [General] Drop-down: focus on text box if exists
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
Labels: enhancement

#694 Create a new dist version 0.9.17
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#695 Impl [Nuclio] Various text changes (tooltips, placeholders, etc.)
  src/i18n/en/functions.json
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/function-event-dialog/function-event-dialog.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
Labels: enhancement

#696 Create a new dist version 0.9.18
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#697 Impl [General] More-info: use default cursor when opens on hover
  src/igz_controls/components/more-info/more-info.less
Labels: enhancement

#698 Impl [Nuclio] Config>Resources: Change tooltip text of GPU limit
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#699 Create a new dist version 0.9.19
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#701 Impl [General] Drop-down: autocomplete by contains or prefix
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
Labels: Cleanup, enhancement

#700 [Services] Presto: Custom Params: Add Advanced section
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/less/buttons.less
  src/igz_controls/services/dialogs.service.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/less/general-rules.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
Labels: enhancement

#702 Create a new dist version 0.9.20
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#703 Impl [Nuclio] Create Shell from scratch: Set default source code
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
Labels: enhancement
