Repository iguazio/dashboard-controls, pull requests merged in 2019-09, with the labels that each got.

#704 Impl [Nuclio] Triggers>Cron: Remove milliseconds from placeholder
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#705 Create a new dist version 0.9.21
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#707 [Browse] Table view: convert chips input to drop-down menu
  src/i18n/en/common.json
Labels: enhancement

#706 [Services] Add Memory, CPU and Logs columns
  src/i18n/en/common.json
  src/igz_controls/components/search-input/search-input.component.js
Labels: enhancement

#708 Create a new dist version 0.9.22
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#709 [Nuclio] Add Invocation, Memory & CPU columns
  src/i18n/en/functions.json
  src/igz_controls/components/element-loading-status/element-loading-status.component.js
  src/igz_controls/components/element-loading-status/element-loading-status.component.spec.js
  src/igz_controls/components/element-loading-status/element-loading-status.less
  src/igz_controls/components/element-loading-status/element-loading-status.tpl.html
  src/igz_controls/components/size/size.component.js
  src/igz_controls/components/size/size.less
  src/igz_controls/components/size/size.tpl.html
  src/igz_controls/services/element-loading-status.service.js
  src/igz_controls/services/element-loading-status.service.spec.js
  src/igz_controls/services/scale.filter.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.spec.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: enhancement

#710 Fix [Build] Lint error
  src/nuclio/projects/project/functions/functions.component.js
Labels: bug

#711 Create a new dist version 0.9.23
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#712 [Nuclio] Use server errors only
  src/i18n/en/functions.json
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/services/export.service.js
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.js
  src/nuclio/projects/new-project-dialog/new-project-dialog.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
Labels: enhancement

#713 Create a new dist version 0.9.24
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#714 Impl [General] Add CPU cores chart config
  src/i18n/en/common.json
  src/igz_controls/components/size/size.component.js
  src/igz_controls/services/scale.filter.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: enhancement

#716 Create a new dist version 0.9.25
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#724 Invocation column moved out of demo mode
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: bug

#720 [General] Dropdown empty options list issue
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
Labels: bug

#723 [Nuclio] Function status icon hides for small browser resolution
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/function.less
  src/nuclio/projects/project/functions/functions.tpl.html
Labels: bug

#725 Create a new dist version 0.9.27
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#722 [Browse] Table view is stuck when page attributes count > 50
  src/igz_controls/directives/resizable-row-cells.directive.js
  src/igz_controls/directives/resizable-table-column.directive.js
  src/igz_controls/services/common-table.service.js
Labels: enhancement

#726 Create a new dist version 0.9.28
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#730 Create a new dist version 0.9.29
  dist/images/ic-alert-message.svg
  dist/images/shape.svg
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#732 Create a new dist version 0.9.30
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug
