Repository iguazio/dashboard-controls, pull requests merged in 2019-04, with the labels that each got.

#530 IG-2205 [Nuclio] Triggers>Cron>Schedule: display all 6 values
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
Labels: enhancement

#532 IG-2209 [Logs] Filter pane: Enter key to apply filters
  src/igz_controls/components/search-input/search-input.component.js
  src/igz_controls/components/search-input/search-input.tpl.html
Labels: enhancement

#533 Create a new dist version 0.6.14
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#531 IG-2206 [Nuclio] Create Function from template: unused space
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
Labels: enhancement

#534 IG-2212 [Nuclio] Load function when deploy completed
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#535 IG-2213 [Data-Access-Policy][Data-Lifecycle] Path input icon overflow
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#536 Create a new dist version 0.6.15
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#537 Impl [Nuclio] Configuration: Volumes: Remove "Host Path" class
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#538 Impl [Nuclio] Configuration>Resources>GPU: "Per replica" tooltip
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#539 Impl [Nuclio] Add tooltips to "Disable Cache" and "No Internet"
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#540 Impl [Nuclio] Create function: update background image
  src/igz_controls/images/nuclio.png
Labels: enhancement

#541 Create a new dist version 0.6.16
  dist/images/nuclio.png
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#543 IG-2183 [General] Add IGZ_E2E_TESTING verification for unload-page.service.js
  src/igz_controls/services/unload-page.service.js
Labels: enhancement

#542 item-cell-sub-text typo-fix
  src/igz_controls/less/table.less
Labels: Cleanup

#545 Fix placeholder in 'igzSearchInput'
  src/igz_controls/components/search-input/search-input.less
Labels: enhancement

#544 IG-2217 [Services] Jupyter Notebook: add Flavor & env vars
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/less/general-rules.less
  src/nuclio/projects/project/functions/version/version.less
Labels: enhancement

#546 IG-2216 [Nuclio] Template Parameters dialog: move labels to left
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
Labels: enhancement

#547 IG-2219 [Nuclio] Hide columns headers when list is empty
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.tpl.html
Labels: enhancement

#548 Create a new dist version 0.7.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#549 IG-2222 [Nuclio] Change Readiness Timeout minimum value from 0 to 1
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#550 IG-2220 [Nuclio] Re-order configuration panes
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.component.js
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.tpl.html
Labels: enhancement

#551 Create a new dist version 0.7.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#552 IG-2214 [Clusters][Nodes] Add app clusters and app nodes
  src/igz_controls/less/igz-grid.less
Labels: enhancement

#553 Impl [General] Validating input field: reduce debounce to 200ms
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
Labels: enhancement

#554 Create a new dist version 0.7.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#555 IG-2225 [General] "More info" icon: make as common component
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
  src/igz_controls/less/dialogs.less
  src/igz_controls/less/general-rules.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.less
Labels: enhancement

#556 Create a new dist version 0.8.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#557 IG-2240 [Nuclio] Monaco editor scrollbar flickers on Firefox
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: bug

#558 IG-2242 [Nuclio] Configuration: Make text-areas scrollable
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.less
Labels: enhancement

#560 IG-2241 [Nuclio] Commands: quotes are doubled in request after import
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/common/services/export.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: bug

#561 Impl [Nuclio] Create function from scratch: Remove some defaults
  src/igz_controls/components/slider-input-block/slider-input-block.less
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#559 IG-2243 [General] Number input: brighten placeholder text color
  src/igz_controls/components/number-input/number-input.less
Labels: enhancement

#562 Create a new dist version 0.8.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#563 Impl [Nuclio] Configuration: Build: disable pane for Edit Online
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/igz_controls/less/inputs.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement
