Repository iguazio/dashboard-controls, pull requests merged in 2019-02, with the labels that each got.

#438 IG-2091 [Nuclio] Triggers: Http: Add secret to ingresses
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
Labels: enhancement

#440 Impl [Nuclio] Expect 409 Display Name violation error on creation
  src/nuclio/projects/new-project-dialog/new-project-dialog.component.js
Labels: enhancement

#441 Impl [Nuclio] Display function deploy errors in pop-up dialog
  src/nuclio/projects/edit-project-dialog/edit-project-dialog.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#439 IG-2081 [Services] Description hidden on column resize
  src/igz_controls/directives/multiline-ellipsis.directive.js
  src/igz_controls/directives/resizable-table-column.directive.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
Labels: bug

#442 Create a new dist version 0.5.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#443 IG-1811 [Nuclio] Drop-down menu visual issue
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-logging/version-configuration-logging.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/project/functions/version/version.less
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: bug

#444 IG-2097 [Services][Nuclio] Apply new action icon style
  src/igz_controls/components/action-panel/action-panel.less
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: enhancement

#446 Create a new dist version 0.5.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#447 IG-2112 [Services] Disable "Refresh" while applying changes
  src/igz_controls/components/action-item/action-item-refresh/action-item-refresh.component.js
  src/igz_controls/components/action-item/action-item-refresh/action-item-refresh.tpl.html
Labels: enhancement

#448 Create a new dist version 0.5.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#450 IG-1811 [Nuclio] Drop-down menu visual issue
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
Labels: bug

#451 IG-2117 [Nuclio] Show "Delete" up-front, out of context menu
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.less
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
Labels: enhancement

#452 Create a new dist version 0.5.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#453 IG-2128 [General] Dropdown: add Disabled property to option
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
Labels: enhancement

#454 Create a new dist version 0.5.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#455 Fix [Nuclio] Status and port number not updating on Refresh
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
Labels: bug

#456 Create a new dist version 0.5.8
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#461 Fix [Nuclio] Should not allow to start function name with a digit
  src/igz_controls/services/validating-patterns.service.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
Labels: bug

#459 IG-2131 [General] Use common link style
  src/igz_controls/less/dialogs.less
  src/igz_controls/less/helpers.less
Labels: enhancement

#457 IG-2127 [General] Remove duplication for copy-to-clipboard
  src/igz_controls/components/copy-to-clipboard/copy-to-clipboard.component.js
  src/igz_controls/components/copy-to-clipboard/copy-to-clipboard.tpl.html
  src/nuclio/common/components/function-config-dialog/function-config-dialog.component.js
  src/nuclio/common/components/function-config-dialog/function-config-dialog.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: Cleanup, enhancement

#463 IG-2126 [General] Number Input:properly set width
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/components/number-input/number-input.less
  src/igz_controls/components/number-input/number-input.tpl.html
Labels: enhancement

#464 Create a new dist version 0.5.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#466 Impl [General] Bump bootstrap to 3.4.1 for security fix
  package.json
Labels: enhancement

#458 IG-2121 [Nuclio] Visual bug in Code tab in Safari
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: bug

#465 IG-2131 fixed placement of 'external link' icon
  src/igz_controls/less/helpers.less
  src/igz_controls/less/icons.less
Labels: enhancement

#467 General validating input placeholder and focus color
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: enhancement

#468 Impl [Nuclio] Triggers screen: do not crop list after 500 pixels
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.less
Labels: enhancement

#469 Create a new dist version 0.5.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
