Repository iguazio/dashboard-controls, pull requests merged in 2019-03, with the labels that each got.

#473 IG-2145 [Nuclio] Triggers>Cron>Schedule: tweak seconds in formula
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
Labels: bug

#470 Fixed isItemChanged property in default dropdown
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
Labels: enhancement

#471 IG-2139 [Nuclio] Create new item with 1 click when collapsed
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#477 Create a new dist version 0.5.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#472 IG-2142 [Nuclio] Status tab: update contents while deploying
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-navigation-tabs/test-events-navigation-tabs.less
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.component.js
  src/nuclio/projects/project/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#480 Create a new dist version 0.5.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#475 IG-2143 [Services] Add "Undo" icons and actions
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#481 Create a new dist version 0.6.0
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#483 Impl [General] Upgrade momentjs and lodash packages for security
  package.json
Labels: enhancement

#482 IG-2151 [General] igzValidatingInputField: hide counter if disabled
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: enhancement

#484 Fix igzInputOnlyValidCharacters directive
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/igz_controls/directives/input-only-valid-characters.js
Labels: bug

#445 IG-2092 [Nuclio] Configuration: Resources: Add request+limit
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#485 Create a new dist version 0.6.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#486 IG-1617 [Data Access Policy][Data Lifecycle] Refresh browser
  src/igz_controls/services/unload-page.service.js
Labels: enhancement

#487 IG-1617 comments fix
  src/igz_controls/services/unload-page.service.js
Labels: Cleanup

#488 Create a new dist version 0.6.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#449 IG-2115 [General] Use new "more info" icon
  src/igz_controls/components/slider-input-block/slider-input-block.less
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/dialogs.less
  src/igz_controls/less/general-rules.less
  src/igz_controls/less/icons.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.less
Labels: enhancement

#490 Impl [General] `igzActionPanel`: remove right margin of last item
  src/igz_controls/components/action-panel/action-panel.less
Labels: enhancement

#489 IG-2163 [Nuclio] Configuration: Resources: Add "GPU" field
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#491 Create a new dist version 0.6.3
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#492 IG-2160 [Services] Presto: Replace "Keys" icon
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/nuclio/projects/projects-table-row/projects-table-row.component.js
  src/nuclio/projects/projects.component.js
Labels: enhancement

#493 Create a new dist version 0.6.4
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#496 Fix [General] Tooltips flickr when they open over the mouse cursor
  src/igz_controls/less/tooltips.less
Labels: bug

#497 IG-2156 [Nuclio] Add "Duplicate" action to functions
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.less
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.component.spec.js
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#498 IG-2171 [Logs] "Control Panel" in staging to "Logs" in production (& IG-2173)
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
Labels: enhancement

#500 IG-2169 [Nuclio] Add "Import project" to welcome screen
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.component.js
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.component.spec.js
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.less
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.tpl.html
  src/nuclio/projects/projects.component.js
Labels: enhancement

#494 IG-2167 [General] `igzNumberInput`: Up arrow on empty starts from min
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/components/number-input/number-input.less
  src/igz_controls/components/number-input/number-input.tpl.html
  src/nuclio/projects/projects.component.spec.js
Labels: enhancement

#501 Create a new dist version 0.6.5
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#499 [Nuclio] Add session key for "Archive" code-entry type
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#502 Impl [Nuclio] Add container & sub-path to V3IO volume
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#503 Create a new dist version 0.6.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#504 IG-2166 [General] Add common table cell sub-text style
  src/igz_controls/less/table.less
Labels: enhancement

#505 Create a new dist version 0.6.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#506 IG-2170 [Nuclio] Collapsible items collapse on drop-down selection
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/igz_controls/components/default-dropdown/default-dropdown.tpl.html
Labels: bug

#507 Create a new dist version 0.6.8
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#508 Fix [General] Action item: Tooltip opens only on hover on icon
  src/igz_controls/components/action-item/action-item.tpl.html
Labels: bug

#511 IG-2181 [Nuclio] Configuration: Resources: Remove GPU Request field
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#510 IG-2175 [Nuclio] Quotes corrupted on import/export
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: bug

#509 IG-2174 [Nuclio] Import multiple-projects YAML not working
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.component.js
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.less
  src/nuclio/projects/projects-welcome-page/projects-welcome-page.tpl.html
  src/nuclio/projects/projects.component.js
Labels: bug, enhancement

#513 Impl [Nuclio] Add Token to Github code-entry type
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#514 Create a new dist version 0.6.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#515 Impl [Nuclio] Move "V3IO" text from Archive to Access Key field
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#516 Create a new dist version 0.6.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#517 Impl [Nuclio] Triggers: Move "Worker Allocator Name" to be last
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#518 Impl [Nuclio] Configuration > Volumes: Refactor V3IO type
  src/igz_controls/less/table.less
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
Labels: enhancement

#519 Create a new dist version 0.6.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#520 [Common] Refactor increase/decrease methods
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/components/number-input/number-input.component.spec.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#521 Create a new dist version 0.6.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#522 IG-2186 [Nuclio] Canceling duplicate shouldn't reload functions list
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
Labels: bug

#523 IG-2185 [General] Pagination input doesn't set any value
  src/igz_controls/components/pagination/pagination.component.js
  src/igz_controls/components/pagination/pagination.component.tpl.html
Labels: bug

#524 Fix [Nuclio] View/Export to YAML has `$$hashKey` properties
  src/nuclio/common/services/export.service.js
Labels: bug

#525 Create a new dist version 0.6.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#526 IG-2189 [Nuclio] Functions action menu issue
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/projects/project/functions/function-collapsing-row/function-version-row/function-version-row.component.js
Labels: bug

#527 IG-2193 [Nuclio] Remove border of "Create new … (+)"
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-data-bindings/version-configuration-data-bindings.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.less
  src/nuclio/projects/project/functions/version/version.less
Labels: enhancement

#528 IG-2194 [General] Number input arrows visual bug on Firefox
  src/igz_controls/components/number-input/number-input.less
  src/igz_controls/components/number-input/number-input.tpl.html
  src/igz_controls/less/helpers.less
Labels: enhancement

#529 Nuclio triggers cron schedule use 0 instead of asterisk for seconds
  src/nuclio/projects/project/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement
