Repository iguazio/dashboard-controls, pull requests merged in 2019-06, with the labels that each got.

#601 IG-2281 [Nuclio] Use `ng-attr` for conditional scrollbars
  src/igz_controls/directives/ng-scrollbars-config.directive.js
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/version-configuration.less
Labels: Cleanup, enhancement

#602 Fix [General] Tenant name validation pattern is wrong
  src/igz_controls/services/validating-patterns.service.js
Labels: bug

#603 Create a new dist version 0.8.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#605 Impl [Nuclio] Remove default value of Readniess Timeout (seconds)
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: enhancement

#600 IG-2283 [Nuclio] Add S3 code entry type
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#604 IG-2293 [Nuclio] Trigger expand/collapse console error
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: bug

#606 IG-2294 [Nuclio] Expanded trigger collapses after clicking/dragging scroll
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: bug

#608 IG-2292 [Nuclio] Configuration: Add explanatory tooltips to panes
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/less/tooltips.less
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.less
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
Labels: enhancement

#609 Create a new dist version 0.8.14
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#610 IG-2301 [Nuclio] Breadcrumbs: Remove unnecessary code
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.tpl.html
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/services/nuclio-header.service.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: Cleanup

#611 IG-2300 [Nuclio] Code: tab not scrollable
  src/nuclio/projects/project/functions/version/version-code/version-code.component.js
  src/nuclio/projects/project/functions/version/version-code/version-code.less
  src/nuclio/projects/project/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#607 IG-2297 [Nuclio] Test pane>Request>Headers: borders falsely displayed
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
Labels: bug

#612 [Nuclio] Fields not marked invalid on switching tabs
  src/nuclio/common/components/key-value-input/key-value-input.component.js
Labels: bug

#614 Fix [General] Some syntax error in router code for testing
  src/iguazio.dashboard-controls.route.js
Labels: bug

#616 IG-2309 [Nuclio] Clicking outside new item does not apply it
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: bug

#613 IG-2295 [Clusters] Add new "Support logs" tab
  src/igz_controls/components/pagination/pagination.controller.js
Labels: enhancement

#615 IG-2302 [General] Display column resize handles
  src/igz_controls/directives/resizable-row-cells.directive.js
  src/igz_controls/directives/resizable-table-column.directive.js
  src/igz_controls/less/igz-grid.less
Labels: enhancement

#619 IG-2310 [Nuclio] Labels/annotations start as invalid
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: bug

#617 IG-2306 [General] CSS classes organizing
  src/igz_controls/less/general-rules.less
  src/igz_controls/less/ng-scrollbars.less
  src/igz_controls/less/table.less
Labels: Cleanup

#618 IG-2303 Kill `third-party-components.service.js`
  src/igz_controls/services/angular-base64.service.js
  src/igz_controls/services/angular-moment.service.js
Labels: Cleanup

#620 Create a new dist version 0.8.15
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#622 Fix [General] Tenant name must end with alphanumeric character
  src/igz_controls/services/validating-patterns.service.js
Labels: bug

#623 Create a new dist version 0.8.16
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#624 Impl [Nuclio] Configuration: add/edit tooltips
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: enhancement

#625 Create a new dist version 0.8.17
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#626 IG-2308 [Nuclio] Function import broken on Projects screen
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
Labels: bug

#627 IG-2307 Renaming the `ConvertorService` to `ConverterService`
  src/igz_controls/components/slider-input-block/slider-input-block.component.js
  src/igz_controls/components/slider-input-block/slider-input-block.component.spec.js
  src/igz_controls/services/convertor-service.js
  src/nuclio/common/services/converter.service.js
  src/nuclio/common/services/converter.service.spec.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: Cleanup

#628 Create a new dist version 0.8.18
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#629 [Nuclio] Empty required field not disabling "Deploy"
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
Labels: bug

#630 Create a new dist version 0.8.19
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#632 Impl [Pagination] Prevent flicker on page load (do not clear list)
  src/igz_controls/components/pagination/pagination.controller.js
Labels: enhancement

#631 [Nuclio] Projects Welcome screen console error issue
  src/igz_controls/directives/resizable-table-column.directive.js
Labels: bug

#633 Revert [Pagination] Prevent flicker on page load (do not clear list)
  src/igz_controls/components/pagination/pagination.controller.js
Labels: revert

#634 Impl [Nuclio] Remove default value from "Readiness Timeout"
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#635 Create a new dist version 0.8.20
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#636 [Nuclio] New added trigger displays incorrect info
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: bug

#638 Create a new dist version 0.9.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
