Repository iguazio/dashboard-controls, pull requests merged in 2019-10, with the labels that each got.

#751 [Nuclio] Creating a new function from template not working
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
Labels: bug

#752 Create a new dist version 0.9.37
  dist/images/ic-alert-message.svg
  dist/images/shape.svg
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#754 Revert [Build] Mistakenly changed dist image files
  dist/images/ic-alert-message.svg
  dist/images/shape.svg
Labels: bug, revert

#755 Create a new dist version 0.9.38
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: revert

#746 [Nuclio] Dropdown visual issue
  src/nuclio/common/components/edit-item/edit-item.less
Labels: bug

#728 [Data Lifecycle] Policy details Schedule dropdown opens incorrect
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
Labels: bug

#727 [Nuclio] Duplicate function dialog Name input counter doesn't display
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#758 [Nuclio] New function name input delay
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
Labels: bug

#733 [Clusters] Split data and app to different tabs
  src/i18n/en/common.json
Labels: enhancement

#760 [Nuclio] Add tooltip to disabled deploy button
  src/i18n/en/functions.json
  src/nuclio/projects/project/functions/version/version.component.js
  src/nuclio/projects/project/functions/version/version.tpl.html
Labels: enhancement

#762 Create a new dist version 0.9.39
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#763 Fix [General] Scale filter: values < 1 return wrong result
  src/igz_controls/services/scale.filter.js
Labels: bug

#745 [General] Text box: Add validation rules pop-up
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#764 [Nuclio] Switching tabs bypasses Disabled Deploy button
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
Labels: bug

#765 Impl [General] Validating input: hide validation icon on no rules
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: Cleanup, enhancement

#766 Fix [General] Scale filter: values<1 return wrong result (nanos)
  src/igz_controls/services/scale.filter.js
Labels: bug

#767 Create a new dist version 0.9.40
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#768 Impl [Nuclio] Configuration: Build: Disable pane for Image only
  src/i18n/en/functions.json
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#769 Impl [General] Disallow env var to start with `.` for Jupyter
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#759 [Services] Edited file confirm dialog does not appear after 'Esc' click
  src/igz_controls/services/close-dialog.service.js
  src/igz_controls/services/dialogs.service.js
Labels: bug

#756 [Services] CPU graphics don't change after column resize
  src/igz_controls/components/size/size.component.js
Labels: bug

#770 Create a new dist version 0.10.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
