Repository iguazio/dashboard-controls, pull requests merged in 2019-01, with the labels that each got.

#413 Fix [Nuclio] Logs are missing in Test pane
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#414 Create a new dist version 0.4.14
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#415 IG-2065 [Nuclio] Request body is not cleared on clicking "+"
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#416 IG-2066 [Nuclio] Test pane: Pinned mode is broken
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: bug

#418 Fix [Nuclio] Templates: drop-down params not populating properly
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
Labels: bug

#419 Create a new dist version 0.4.15
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#417 added reports icon
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#420 Fix [Nuclio] "Discard changes?" on screen leave falsely displayed
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug

#421 Create a new dist version 0.4.16
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#423 IG-2080 [General] Dashboard-controls: Unit tests are broken
  src/nuclio/projects/projects.component.spec.js
Labels: bug

#428 Create a new dist version 0.4.18
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#422 IG-2075 [General] Hide "Scanned Items" column in production mode
  src/igz_controls/less/igz-grid.less
  src/igz_controls/services/common-table.service.js
  src/igz_controls/services/common-table.service.spec.js
  src/nuclio/projects/project/functions/functions.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/projects-table-row/projects-table-row.component.spec.js
  src/nuclio/projects/projects.component.js
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#424 IG-2073 [General] Apply action icons styles by design
  src/igz_controls/components/action-menu/action-menu.less
  src/igz_controls/components/action-panel/action-panel.less
  src/igz_controls/components/actions-panes/actions-panes.component.js
  src/igz_controls/components/actions-panes/actions-panes.tpl.html
  src/igz_controls/components/sort-dropdown/sort-dropdown.tpl.html
  src/igz_controls/less/custom-dropdown.less
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.less
  src/nuclio/common/components/monaco/text-size-dropdown/text-size-dropdown.tpl.html
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.tpl.html
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/projects.tpl.html
Labels: enhancement

#429 Create a new dist version 0.5.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#430 Fix [Nuclio] Test pane logs: visual bug on expanding entry
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/test-events-logs/test-events-logs.less
Labels: bug

#432 IG-2088 [Services] Use new "Restart" icon
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#436 Fix [Nuclio] Lint error
  src/nuclio/projects/project/functions/version/version.component.js
Labels: bug
