Repository iguazio/dashboard-controls, pull requests merged in 2019-07, with the labels that each got.

#640 [General] More info on click: close tooltip on click outside
  src/igz_controls/components/more-info/more-info.component.js
Labels: enhancement

#641 [Nuclio] Readiness Timeout is invalid but Deploy is enabled
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: bug

#642 Impl [General] Several text changes/corrections
  src/i18n/en/functions.json
  src/i18n/en/services.json
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/projects/project/functions/functions.service.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/projects/project/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
Labels: bug, enhancement

#644 Create a new dist version v0.8.22
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#639 [Nuclio] Test pane: disable "Test" button if in standby
  src/i18n/en/functions.json
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/projects/project/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: enhancement

#643 [Nuclio] Duplicate function: go to function, no auto-deploy
  src/nuclio/projects/project/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/projects/project/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/projects/project/functions/functions.tpl.html
  src/nuclio/projects/project/functions/version/version.component.js
Labels: enhancement

#645 Create a new dist version 0.9.1
  dist/i18n/en/functions.json
  dist/i18n/en/services.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#646 Impl [General] Improve username and tenant name validation RegEx
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#647 Create a new dist version 0.9.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#648 [i18n] Move messages from dashboard-controls to dashboard
  src/i18n/en/clusters.json
  src/i18n/en/common.json
  src/i18n/en/containers.json
  src/i18n/en/events.json
  src/i18n/en/header.json
  src/i18n/en/home.json
  src/i18n/en/identity.json
  src/i18n/en/login.json
  src/i18n/en/logs.json
  src/i18n/en/networks.json
  src/i18n/en/services.json
  src/i18n/en/storagePools.json
  src/i18n/en/tasks.json
  src/i18n/en/tenants.json
Labels: enhancement

#649 Create a new dist version 0.9.3
  dist/i18n/en/clusters.json
  dist/i18n/en/common.json
  dist/i18n/en/containers.json
  dist/i18n/en/events.json
  dist/i18n/en/header.json
  dist/i18n/en/home.json
  dist/i18n/en/identity.json
  dist/i18n/en/login.json
  dist/i18n/en/logs.json
  dist/i18n/en/networks.json
  dist/i18n/en/services.json
  dist/i18n/en/storagePools.json
  dist/i18n/en/tasks.json
  dist/i18n/en/tenants.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#650 Impl [General] Allow underscores in browse attribute name
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#651 Create a new dist version 0.9.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#652 [i18n] Remove i18n warnings from unit-tests output
  build.config.js
  gulpfile.js
Labels: enhancement

#654 [Audit] Upper pane period drop down contains incorrect options; Upper pane visual bugs
  src/igz_controls/less/tooltips.less
Labels: enhancement

#655 Create a new dist version 0.9.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#656 Fix [Pagination] Numbers ending with zeros are falsely disallowed
  src/igz_controls/components/pagination/pagination.component.js
Labels: bug

#657 [Users] Edit password dialog displays incorrect error messages; [Overview] Delete interface confirm dialog displays incorrect text
  src/i18n/en/common.json
Labels: bug

#653 [Nuclio] Create function: minor redesign
  src/i18n/en/functions.json
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.less
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.less
  src/nuclio/common/screens/create-function/function-import/function-import.tpl.html
Labels: enhancement

#658 Create a new dist version 0.9.6
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#660 [Nuclio] Create function: pagination width issue
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
Labels: bug

#659 [Browse] Add new table view
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#661 Create a new dist version 0.9.7
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#663 [Build] Deprecate gulp-util (use fancy-log and ansi-colors)
  package.json
Labels: Cleanup

#664 Create a new dist version 0.9.8
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup

#665 Impl [General] Allow underscores in browse attribute name
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#666 Create a new dist version 0.8.23
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#668 [Nuclio] Wrong breadcrumbs color on hover
  src/nuclio/common/components/breadcrumbs/breadcrumbs.less
Labels: bug

#669 Create a new dist version 0.9.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#671 [Browse] Upload button not always works
  src/igz_controls/components/action-item/action-item.tpl.html
  src/igz_controls/components/action-panel/action-panel.less
Labels: bug

#672 [General] Change email validation pattern
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#674 [Browse] Add attribute-type icons
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#673 [Nuclio] Template Parameters dialog not opening
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
Labels: bug

#667 [i18n] Redesign the language selector drop-down field
  src/i18n/en/common.json
  src/igz_controls/components/default-dropdown/default-dropdown.less
Labels: enhancement

#676 Create a new dist version 0.9.10
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#677 [Nuclio] Template box is cropped when only single row
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.less
Labels: bug

#678 Impl [Pagination] Add a flag to skip emptying list on page load
  src/igz_controls/components/pagination/pagination.controller.js
  src/igz_controls/components/pagination/pagination.service.js
Labels: enhancement

#679 Create a new dist version 0.9.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#680 Impl [General] Add some new common messages
  src/i18n/en/common.json
Labels: enhancement

#681 Create a new dist version 0.9.12
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
