Repository iguazio/dashboard-controls, pull requests merged in 2020-01, with the labels that each got.

#848 Fix [Nuclio] UI stuck on entering long labels/annotations keys
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: bug

#849 Create a new dist version 0.15.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#850 Fix [Nuclio] Wrong validation rules for lables & annotations
  src/igz_controls/services/validating-patterns.service.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: bug

#851 Fix [Nuclio] Lint warnings
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: bug

#852 Create a new dist version 0.15.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#854 [API Gateways] Add creation/edit wizard
  src/igz_controls/components/copy-to-clipboard/copy-to-clipboard.component.js
  src/igz_controls/components/copy-to-clipboard/copy-to-clipboard.tpl.html
Labels: enhancement

#855 Create a new dist version 0.15.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#856 [Services] Presto>Advanced section input validation pop-up cuts
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: enhancement

#857 [Projects] Remove "New function" button & auto-create logic
  src/nuclio/functions/functions.component.js
Labels: enhancement

#858 [General] igzKeyValueInput: text overlaps validation icon
  src/nuclio/common/components/key-value-input/key-value-input.less
Labels: bug

#859 [Browse] HTML viewer doesn't close on Esc
  src/igz_controls/services/dialogs.service.js
Labels: bug

#860 Fix [Projects] Export projects not working
  src/nuclio/common/components/function-config-dialog/function-config-dialog.component.js
  src/nuclio/common/services/export.service.js
Labels: bug

#862 [Nuclio] Configuration>Volumes>Mount Path: Up to 255 chars
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: enhancement

#861 [Services] Presto: add Undo action after Reset To Default
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#863 Create a new dist version 0.15.5
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#864 [Nuclio] Import: Add error message on error parsing YAML
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
Labels: bug

#865 Impl [General] Add secondary button style
  src/igz_controls/components/action-panel/action-panel.less
  src/igz_controls/components/default-dropdown/default-dropdown.less
  src/igz_controls/components/info-page/info-page-actions-bar/info-page-actions-bar.less
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.less
  src/igz_controls/components/pagination/pagination.component.js
  src/igz_controls/components/pagination/pagination.component.tpl.html
  src/igz_controls/components/pagination/pagination.less
  src/igz_controls/components/size/size.tpl.html
  src/igz_controls/components/slider-input-block/slider-input-block.less
  src/igz_controls/less/buttons.less
  src/igz_controls/less/dialogs.less
  src/igz_controls/less/inputs.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/common/less/buttons.less
  src/nuclio/common/less/dialogs.less
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.less
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.less
  src/nuclio/common/screens/create-function/function-import/function-import.tpl.html
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/functions/functions.tpl.html
  src/nuclio/functions/version/function-event-dialog/function-event-dialog.tpl.html
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build-dialog/version-configuration-build-dialog.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build-dialog/version-configuration-build-dialog.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
  src/nuclio/functions/version/version-triggers/version-triggers.less
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
  src/nuclio/functions/version/version.tpl.html
Labels: Cleanup, bug, enhancement

#866 Create a new dist version 0.16.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#867 [Nuclio] Volumes: text-box does not become valid
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: bug

#868 Impl [Nuclio] Triggers: Max workers as number input + limit
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/functions/functions.service.js
Labels: enhancement

#869 Fix [Nuclio] Navigation tabs background color is wrong
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/functions/version/version-configuration/version-configuration.less
Labels: bug

#870 Create a new dist version 0.16.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#871 Impl [Nuclio] Triggers: Max workers as number input + limit
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#872 Create a new dist version
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#874 Impl [Nuclio] Triggers > Kafka > Consumer Group: make mandatory
  src/nuclio/functions/functions.service.js
Labels: enhancement

#875 Create a new dist version 0.16.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#876 Impl [Nuclio] Triggers > Kafka > Consumer Group: make mandatory
  src/nuclio/projects/project/functions/functions.service.js
Labels: enhancement

#877 Create a new dist version
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#878 [Nuclio] Invalid YAML when viewing function or exporting
  src/nuclio/common/services/export.service.js
Labels: bug

#873 [Project] Action bar is partially hidden on closing header
  src/nuclio/functions/functions.tpl.html
Labels: bug

#880 [Nuclio] Volumes: All volumes with the same name are removed
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
Labels: bug

#881 [Nuclio] Volumes: Mount Path falsely remains invalid
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: bug

#882 Impl [Nuclio] Triggers: Password: conceal characters
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#879 [Nuclio] Add name uniqueness validation to functions
  src/i18n/en/functions.json
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#883 Create a new dist version 0.16.3
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#884 [Nuclio] Action bar disappears
  src/nuclio/functions/functions.tpl.html
Labels: bug

#885 Impl [Nuclio] Triggers>HTTP>Ingresses>Secret: remove red *
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#886 Impl [Nuclio] Triggers: Password: conceal characters
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#887 Create a new dist version v0.9.45
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#888 Create a new dist version 0.16.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
