Repository iguazio/dashboard-controls, pull requests merged in 2020-09, with the labels that each got.

#1080 Fix [igzValidatingInputField] Popup: blocked click below field
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: bug

#1081 Fix [Nuclio] Configuration: Onbuild image description obstructed
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: bug

#1082 Create a new dist version 0.24.8
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1079 [Browse] Missing loader for uploading files
  src/i18n/en/common.json
  src/igz_controls/components/action-item/action-item.component.js
  src/igz_controls/components/splash-screen/splash-screen.component.js
Labels: Cleanup, enhancement

#1083 Create a new dist version 0.25.0
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#1084 [Services] Presto: no trailing slash in Hive Metastore path
  src/i18n/en/common.json
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1085 Create a new dist version 0.25.1
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1086 [Services] Jupyter: Add security context
  src/i18n/en/common.json
Labels: enhancement

#1087 Create a new dist version 0.25.2
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
