Repository iguazio/dashboard-controls, pull requests merged in 2020-12, with the labels that each got.

#1140 [Nuclio] Actions remain disabled after deploy cancel/fail
  src/nuclio/functions/version/version.component.js
Labels: bug

#1141 Impl [Build] HTML: Collapse consecutive spaces into 1, not 0
  gulpfile.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
Labels: enhancement

#1142 Create a new dist version 0.28.10
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1143 Impl [General] Inherit font style of <blockquote> from its parent
  src/igz_controls/less/general-rules.less
Labels: enhancement

#1144 Create a new dist version 0.28.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1147 Fix [igzDefaultDeopdownField] Potential whitespace bug
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
Labels: bug

#1148 Impl [Nuclio] Function: add unique classname to stale version msg
  src/nuclio/functions/functions.service.js
Labels: enhancement

#1146 [Nuclio] Configuration: remove "FS group" field on K8s
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#1145 [API gateways] Get authentication type options from backend
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/nuclio/api-gateways/api-gateways.service.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.tpl.html
Labels: enhancement

#1149 Create a new dist version 0.28.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1150 Fix [Nuclio] Build configuration: image prefix gone after deploy
  src/nuclio/functions/version/version.component.js
Labels: bug

#1151 Create a new dist version 0.28.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1152 [Nuclio] Add message on deleting stale function version
  src/i18n/en/functions.json
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#1153 Create a new dist version 0.28.14
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1154 Impl [Nuclio] Max length of labels in DNS-1123 sub-domain to 63
  src/i18n/en/common.json
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1155 Cleanup [Validation] Service name to be based on DNS-1035 label
  src/igz_controls/services/validation.service.js
Labels: Cleanup

#1156 Cleanup [Nuclio] Duplicate function: rename `name` attr of Name
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
Labels: Cleanup

#1158 Impl [igzMoreInfo] Do not let tooltip be obstructed
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
Labels: enhancement

#1157 [Nuclio] Invocation URL: N/A on error or not exposed, +info
  src/i18n/en/functions.json
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.tpl.html
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.less
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/functions/version/version-monitoring/version-monitoring.component.js
  src/nuclio/functions/version/version-monitoring/version-monitoring.less
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
Labels: enhancement

#1160 Impl [Nuclio] N/A invocation URL for not running, not only error
  src/i18n/en/functions.json
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.less
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/functions/version/version-monitoring/version-monitoring.component.js
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
Labels: enhancement

#1161 Create a new dist version 0.28.15
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#1162 [Triggers] HTTP ingress path must start with a slash
  src/igz_controls/services/validation.service.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#1159 [Nuclio] Breaks on /projects/
  src/iguazio.dashboard-controls.route.js
Labels: bug

#1163 [External OAuth] Add regenerate button
  src/i18n/en/common.json
Labels: enhancement

#1166 Fix [igzMoreInfo] Description not updating if HTML is enabled
  src/igz_controls/components/more-info/more-info.component.js
Labels: bug

#1164 [Nuclio] Layout breaks on window resize with closed test pane
  build.config.js
  package.json
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/functions/version/version-code/version-code.component.js
  src/nuclio/functions/version/version-code/version-code.less
  src/nuclio/functions/version/version-code/version-code.tpl.html
  src/third-party/angular-ui-layout/ui-layout.js
  src/third-party/angular-ui-layout/ui-layout.less
Labels: bug

#1168 Impl [Nuclio] Pass project from parent instead of fetch async-ly
  src/nuclio/api-gateways/api-gateways.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.spec.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.spec.js
  src/nuclio/functions/functions.component.js
  src/nuclio/functions/functions.component.spec.js
  src/nuclio/functions/version/version.component.js
Labels: Cleanup, enhancement

#1169 Create a new dist version 0.29.0
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/js/vendor.js
  dist/less/iguazio.dashboard-controls.less
  dist/less/vendor.less
  package.json
Labels: Cleanup, bug, enhancement

#1170 Impl [Nuclio] Function: Remove build image name prefix from field
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.spec.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
Labels: enhancement

#1171 Impl [igzElementLoadingStatus] Add `errorMessage` attribute
  src/i18n/en/common.json
  src/igz_controls/components/element-loading-status/element-loading-status.component.js
  src/igz_controls/components/element-loading-status/element-loading-status.tpl.html
Labels: enhancement

#1172 Create a new dist version 0.29.1
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1173 Impl [Nuclio] Hide annotations with key prefix of nuclio.io/
  src/igz_controls/services/form-validation.service.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: enhancement

#1174 Fix [Nuclio] Function: wrong breadcrumbs ("Edit version")
  src/nuclio/functions/version/version.component.js
Labels: bug

#1175 Create a new dist version 0.29.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1176 Impl [Nuclio] Align function states in Status tab header
  src/i18n/en/common.json
  src/nuclio/common/components/navigation-tabs/navigation-tabs.component.js
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
  src/nuclio/common/components/navigation-tabs/navigation-tabs.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/override-function-dialog/override-function-dialog.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version.component.js
  src/nuclio/functions/version/version.tpl.html
Labels: bug, enhancement

#1177 Create a new dist version 0.29.3
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1178 Impl [Nuclio] Enrich function list with API GW only when needed
  src/igz_controls/components/element-loading-status/element-loading-status.component.js
  src/igz_controls/components/element-loading-status/element-loading-status.component.spec.js
  src/nuclio/api-gateways/api-gateways.component.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/services/export.service.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.component.js
  src/nuclio/functions/functions.component.spec.js
  src/nuclio/functions/functions.tpl.html
  src/nuclio/functions/version/version.component.js
Labels: bug, enhancement

#1179 Create a new dist version 0.30.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1180 [Nuclio] Test pane: enable testing when scaled-to-zero
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
Labels: enhancement

#1181 Impl [Nuclio] Function>Volumes: Remove name uniqueness validation
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: enhancement

#1182 Impl [Nuclio] DNS-1123 for name of function/API GW (was DNS-1035)
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1183 Impl [Nuclio] V3IO volume: turn Container Name optional
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#1184 Create a new dist version 0.30.1
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
