Repository iguazio/dashboard-controls, pull requests merged in 2020-10, with the labels that each got.

#1089 [Browse] Console errors when switching folders and views
  src/igz_controls/components/info-page/info-page-content/extend-background/extend-background.directive.js
Labels: bug

#1088 [Nuclio] Configuration: Service Account & security context
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#1090 Create a new dist version 0.25.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1092 Create a new dist version 0.25.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1094 Impl [Nuclio] Basic Settings: omit empty security context props
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
Labels: enhancement

#1095 Create a new dist version 0.25.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1096 [Nuclio] Triggers: add default HTTP trigger & Service Type
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/less/helpers.less
  src/nuclio/common/components/collapsing-row/collapsing-row.less
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.less
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/functions.tpl.html
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#1097 Create a new dist version 0.25.6
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1099 Fix [igzValidatingInputField] Failing unit tests
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
Labels: bug

#1100 Fix [Nuclio] Test pane: Test button disabled for Cluster IP
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#1101 Create a new dist version 0.25.7
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1102 Fix [Nuclio] Wrong conditions for Invocation URL and Test button
  src/i18n/en/functions.json
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/functions/version/version.component.js
Labels: bug, enhancement

#1103 Create a new dist version 0.26.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1104 [Action Menu] Unaligned actions with/without icons
  src/igz_controls/components/action-item/action-item.component.js
  src/igz_controls/components/action-menu/action-menu.less
Labels: enhancement

#1105 Create a new dist version 0.26.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
