Repository iguazio/dashboard-controls, pull requests merged in 2020-08, with the labels that each got.

#1055 [Function] Add refresh button
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-code/version-code.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.spec.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/functions/version/version-monitoring/version-monitoring.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version.component.js
  src/nuclio/functions/version/version.tpl.html
Labels: enhancement

#1061 Create a new dist version 0.24.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1063 [Nuclio] Function creation fails (PUT instead of POST)
  src/nuclio/functions/version/version.component.js
Labels: bug

#1064 Create a new dist version 0.24.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1065 [Data Clusters] Clicking on action in item menu opens info
  src/igz_controls/components/action-item/action-item.component.js
Labels: bug

#1066 [Nuclio] Deploy logger is empty until deploy finishes
  src/nuclio/functions/version/version.component.js
Labels: bug

#1058 [igzAutocomplete][igzInfoPageFilters] Disablable buttons
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.component.js
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.tpl.html
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.component.js
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.tpl.html
Labels: enhancement

#1067 [igzActionItem] Failed unit tests
  src/igz_controls/components/action-item/action-item.component.spec.js
Labels: bug

#1068 Create a new dist version 0.24.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1062 [Nuclio] Triggers: Add "Advanced" section
  src/i18n/en/common.json
  src/nuclio/common/components/edit-item/edit-item-field/edit-item-field.component.js
  src/nuclio/common/components/edit-item/edit-item-field/edit-item-field.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.less
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/functions/functions.service.js
Labels: enhancement

#1069 Create a new dist version 0.24.3
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1070 Fix [Nuclio] Triggers: trigger not collapsing on click bg below
  src/nuclio/common/components/edit-item/edit-item.component.js
Labels: bug

#1071 Create a new dist version 0.24.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1072 [Browse] View dropdown not closing after selecting an option
  src/igz_controls/components/action-item/action-item.component.js
  src/igz_controls/components/action-item/action-item.component.spec.js
Labels: revert

#1073 Create a new dist version 0.24.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: revert

#1074 Impl [Nuclio] Triggers: allow creating new while editing existing
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: enhancement

#1075 Create a new dist version 0.24.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1076 [Nuclio] Allow overriding existing function on creation
  src/i18n/en/functions.json
  src/nuclio/common/screens/create-function/create-function.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/override-function-dialog/override-function-dialog.component.js
  src/nuclio/functions/override-function-dialog/override-function-dialog.less
  src/nuclio/functions/override-function-dialog/override-function-dialog.tpl.html
Labels: enhancement

#1077 Create a new dist version 0.24.7
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
