Repository iguazio/dashboard-controls, pull requests merged in 2020-02, with the labels that each got.

#889 [Services] Add flow: Wake up scaled-to-zero services
  src/igz_controls/components/element-loading-status/element-loading-status.component.js
  src/igz_controls/components/element-loading-status/element-loading-status.tpl.html
  src/igz_controls/less/helpers.less
Labels: enhancement

#890 Create a new dist version 0.16.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#892 Impl [Nuclio] Configuration: Image name: Add prefix + default
  src/i18n/en/functions.json
  src/igz_controls/less/helpers.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#891 [Nuclio] Triggers: Validate no more than one HTTP trigger
  src/i18n/en/functions.json
  src/igz_controls/components/default-dropdown/default-dropdown.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: enhancement

#896 Impl [Nuclio] Test pane: default event request body type to text
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: enhancement

#895 [Nuclio] Status column sorts only after second click
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.tpl.html
Labels: bug

#894 [Nuclio] Action bar partially hidden after delete trigger
  src/nuclio/functions/function/ncl-function.tpl.html
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: bug

#893 [Nuclio] Labels: add informative tooltip when disabled
  src/i18n/en/functions.json
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
Labels: enhancement

#897 Create a new dist version 0.16.6
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#899 [App Clusters] Add "Status dashboard" column
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
Labels: enhancement

#900 Create a new dist version 0.16.7
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#901 [Nuclio] Configuration: Name/key not styled as invalid
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#903 Impl [Nuclio] Triggers: v3io Stream: Add Max Workers and Timeout
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/functions/functions.service.js
Labels: enhancement

#904 Create a new dist version 0.9.46
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#905 Impl [General] Add validation rule lists
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#908 Create a new dist version 0.16.8
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#911 Fix [General] Wrong validation rule for K8s DNS1123 sub-domains
  src/i18n/en/common.json
  src/igz_controls/services/validating-patterns.service.js
Labels: bug

#909 [Services] Web APIs: Add "Number of workers" field
  src/igz_controls/components/number-input/number-input.component.js
Labels: enhancement

#910 [Nuclio] Volumes: hide Secret Name/Access Key when collapsed
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
Labels: enhancement

#902 [Nuclio] Change tooltip while deploy in-progress
  src/i18n/en/functions.json
  src/nuclio/functions/version/version.tpl.html
Labels: enhancement

#912 Create a new dist version 0.16.9
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#914 [API GWs] Add auto-complete to function names
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
Labels: enhancement

#913 [Nuclio] Add validation rules to env vars and ingress hosts
  src/i18n/en/functions.json
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: enhancement

#916 Create a new dist version 0.16.10
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#918 Impl [Nuclio] Triggers: Disallow "*" in HTTP ingress host
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#917 [Nuclio] Configuration>Env vars: Name falsely remains invalid
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
Labels: bug

#919 Create a new dist version 0.16.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#920 Impl [Dialogs] Add class names to alert, confirm and prompt
  src/igz_controls/services/dialogs.service.js
Labels: enhancement

#921 Create a new dist version 0.16.12
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
