Repository iguazio/dashboard-controls, pull requests merged in 2020-05, with the labels that each got.

#978 Fix [igzSize] Console error when leaving screen (inconsistent)
  src/igz_controls/components/size/size.component.js
Labels: bug

#979 Cleanup [General] Remove unnecessary `ng-cloak` CSS rule
  src/igz_controls/less/general-rules.less
Labels: Cleanup

#980 Impl [igzValidatePasswordConfirmation] Move component to this repo
  src/igz_controls/directives/validate-password-confirmation.directive.js
Labels: enhancement

#981 Fix [igzValidatePasswordConfirmation] Wrong module name
  src/igz_controls/directives/validate-password-confirmation.directive.js
Labels: bug

#982 Impl [igzValidatingInputField] Add `tooltip` attribute + more
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: Cleanup, enhancement

#983 Create a new dist version 0.20.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#984 Cleanup [igzValidatingInputField] Add doc to `tooltip` attribute
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: Cleanup

#985 Impl [igzActionItem] Add `testId` property to actions
  src/igz_controls/components/action-item/action-item.tpl.html
Labels: enhancement

#986 Fix [igzValidatingInputField] Cannot share validation rules
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#987 Impl [EventHelperService] Add `getFocusedElement` method for blur
  src/igz_controls/services/event-helper.service.js
Labels: enhancement

#988 Create a new dist version 0.20.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#989 [General] Use validation rules instead of patterns
  src/i18n/en/common.json
  src/igz_controls/components/elastic-input-field/elastic-input-field.component.js
  src/igz_controls/components/elastic-input-field/elastic-input-field.component.spec.js
  src/igz_controls/components/elastic-input-field/elastic-input-field.less
  src/igz_controls/components/elastic-input-field/elastic-input-field.tpl.html
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/igz_controls/services/validating-patterns.service.js
  src/igz_controls/services/validation.service.js
  src/igz_controls/services/validation.service.spec.js
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.less
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: Cleanup, enhancement

#990 Impl [igzNumberInput] Refactor: improvements, cleanup, docs
  src/igz_controls/components/number-input/number-input.component.js
  src/igz_controls/components/number-input/number-input.component.spec.js
  src/igz_controls/components/number-input/number-input.less
  src/igz_controls/components/number-input/number-input.tpl.html
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/directives/validate-elevation.directive.js
Labels: Cleanup, enhancement

#991 Impl [igzMoreInfo] Add `isOpen` and `iconType` attributes
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
Labels: enhancement

#992 Impl [Nuclio] Warn when Request is empty while Limit is filled
  src/i18n/en/common.json
  src/igz_controls/less/general-rules.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#993 Create a new dist version 0.21.0
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#994 Impl [igzMoreInfo] Make `isOpen` prop work for hover trigger
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
Labels: enhancement

#995 Create a new dist version 0.21.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#997 Fix [igzActionItemMore] Click area is icon only instead of item
  src/igz_controls/components/action-item/action-item-more/action-item-more.tpl.html
Labels: bug

#998 Impl [i18n] Common: Add "read only" and "read/write" messages
  src/i18n/en/common.json
  src/igz_controls/services/table-size.service.js
Labels: enhancement

#996 [Nuclio] Triggers: Layout breaks on removing a trigger
  src/i18n/en/functions.json
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/functions/functions.component.js
  src/nuclio/functions/functions.tpl.html
  src/nuclio/functions/version/version-code/version-code.tpl.html
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
  src/nuclio/functions/version/version.component.js
  src/nuclio/functions/version/version.tpl.html
Labels: bug

#999 Create a new dist version 0.21.2
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1000 Impl [Nuclio] Cron trigger: hide worker fields on K8s platform
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#1001 Create a new dist version 0.21.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1002 Fix [Nuclio] Function "View YAML": no syntax highlighting
  src/nuclio/common/components/function-config-dialog/function-config-dialog.tpl.html
  src/nuclio/functions/version/function-event-dialog/function-event-dialog.tpl.html
Labels: bug

#1003 Cleanup [Monaco] Pass correct theme value to all instances
  src/nuclio/common/components/function-config-dialog/function-config-dialog.component.js
  src/nuclio/common/components/function-config-dialog/function-config-dialog.tpl.html
  src/nuclio/common/directives/monaco-editor/monaco-editor.directive.js
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.tpl.html
  src/nuclio/functions/version/function-event-dialog/function-event-dialog.component.js
Labels: Cleanup

#1004 Impl [igzTextEdit] Move component to this repo
  src/igz_controls/components/text-edit/text-edit.component.js
  src/igz_controls/components/text-edit/text-edit.component.spec.js
  src/igz_controls/components/text-edit/text-edit.less
  src/igz_controls/components/text-edit/text-edit.tpl.html
Labels: enhancement

#1005 Create a new dist version 0.22.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#1006 Fix [igzTextEdit] Failed unit tests
  src/igz_controls/components/text-edit/text-edit.component.spec.js
Labels: bug

#1007 Impl [Validation] Allow ldap:// schema for IdP address
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1008 Create a new dist version 0.22.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1009 Fix [Nuclio] Test pane: Save not working
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#1010 Create a new dist version 0.22.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1011 Fix [igzValidatingInputField] Field not validated on change
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
Labels: bug

#1012 Create a new dist version 0.22.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1013 Impl [Tooltips] For chart tooltips: align values to the right
  src/igz_controls/less/tooltips.less
Labels: enhancement

#1014 Impl [Nuclio] Add "imported" function state
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: enhancement

#1015 Create a new dist version 0.22.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
