Repository iguazio/dashboard-controls, pull requests merged in 2020-11, with the labels that each got.

#1107 Impl [Nuclio] Triggers: add tooltip and test-id to delete button
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: enhancement

#1106 [API GWs] Move screen from Iguazio repo to Nuclio repo
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/igz_controls/components/auto-complete/auto-complete.component.js
  src/igz_controls/components/auto-complete/auto-complete.less
  src/igz_controls/components/auto-complete/auto-complete.spec.js
  src/igz_controls/components/auto-complete/auto-complete.tpl.html
  src/igz_controls/components/navigation-tabs/navigation-tabs.component.js
  src/igz_controls/components/navigation-tabs/navigation-tabs.less
  src/igz_controls/components/navigation-tabs/navigation-tabs.service.js
  src/igz_controls/components/navigation-tabs/navigation-tabs.tpl.html
  src/igz_controls/components/toast-status-panel/toast-status-panel.component.js
  src/igz_controls/components/toast-status-panel/toast-status-panel.component.spec.js
  src/igz_controls/components/toast-status-panel/toast-status-panel.less
  src/igz_controls/components/toast-status-panel/toast-status-panel.tpl.html
  src/igz_controls/images/globe.png
  src/igz_controls/less/new-item-wizard.less
  src/igz_controls/services/general-data.service.js
  src/nuclio/api-gateways/api-gateway-row/api-gateway-row.component.js
  src/nuclio/api-gateways/api-gateway-row/api-gateway-row.less
  src/nuclio/api-gateways/api-gateway-row/api-gateway-row.tpl.html
  src/nuclio/api-gateways/api-gateways.component.js
  src/nuclio/api-gateways/api-gateways.less
  src/nuclio/api-gateways/api-gateways.service.js
  src/nuclio/api-gateways/api-gateways.tpl.html
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.less
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.tpl.html
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/functions/functions.component.js
Labels: enhancement

#1108 Create a new dist version 0.27.0
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1109 [Nuclio] Reserved names disallowed for functions & API GWs
  src/igz_controls/services/validation.service.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
Labels: enhancement

#1110 [Nuclio] Configuration: label must not begin with nuclio.io/
  src/i18n/en/functions.json
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1111 [API gateways] Add "Redirect unauthorized requests" field
  src/i18n/en/functions.json
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.tpl.html
Labels: enhancement

#1113 Impl [Nuclio] Default HTTP trigger: init name to `http`, reword
  src/i18n/en/functions.json
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: bug, enhancement

#1112 [Main nav bar] Redesign main navigation bar
  src/igz_controls/less/general-rules.less
Labels: enhancement

#1114 Create a new dist version 0.28.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1115 Impl [igzMoreInfo] Do not propagate click event; Reduce width
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
Labels: enhancement

#1116 Create a new dist version 0.28.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#1117 Fix [Functions] No invocation URL when HTTP trigger has ingress
  src/nuclio/common/services/version-helper.service.js
Labels: bug

#1118 Create a new dist version 0.28.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1119 [Services] Authenticator: add connectors and token expiry
  src/igz_controls/services/yaml.service.js
  src/nuclio/common/services/export.service.js
Labels: enhancement

#1120 Create a new dist version 0.28.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1121 [API gateways] Hide when on non-K8s platform
  src/igz_controls/components/navigation-tabs/navigation-tabs.service.js
Labels: enhancement

#1122 Create a new dist version 0.28.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1123 [Nuclio] Configuration: allow modify labels on non-K8s
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
Labels: enhancement

#1124 [API GWs] Wizard: add Host field when none provided from BE
  src/i18n/en/functions.json
  src/nuclio/api-gateways/api-gateways.service.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.tpl.html
Labels: enhancement

#1125 Create a new dist version 0.28.5
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1126 Impl [Nuclio] Function introduce Healthy state
  src/nuclio/common/components/navigation-tabs/navigation-tabs.component.js
  src/nuclio/common/components/navigation-tabs/navigation-tabs.tpl.html
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/version/version-monitoring/version-monitoring.component.js
Labels: enhancement

#1127 Create a new dist version 0.28.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1128 [Nuclio] K8s: Override function only in the same project
  src/i18n/en/functions.json
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/functions/functions.service.js
Labels: enhancement

#1129 Create a new dist version 0.28.7
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1130 [Nuclio] Function list: color function status text
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
Labels: enhancement

#1131 [Nuclio] Configuration>Security context: validation & order
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
Labels: enhancement

#1132 Impl [Nuclio] Create function: reword name collision messages
  src/i18n/en/functions.json
  src/nuclio/functions/override-function-dialog/override-function-dialog.tpl.html
Labels: enhancement

#1133 Impl [Nuclio] Use consistent orange color for building status
  src/nuclio/common/components/navigation-tabs/navigation-tabs.less
Labels: enhancement

#1134 Create a new dist version 0.28.8
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1135 [Nuclio] Function: Inform about UI precedence over external
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#1136 Impl [Nuclio] Create function: reword name collision messages
  src/i18n/en/functions.json
  src/nuclio/functions/override-function-dialog/override-function-dialog.tpl.html
Labels: enhancement

#1137 Create a new dist version 0.28.9
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1139 [Nuclio] Create function: pagination not working on filter
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
Labels: bug
