Repository iguazio/dashboard-controls, pull requests merged in 2020-03, with the labels that each got.

#922 Impl [Validation] Add K8s terms max lengths
  src/igz_controls/services/validating-patterns.service.js
Labels: enhancement

#923 Create a new dist version 0.16.13
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#925 [Nuclio] Triggers: Host: Validation rule menu hidden
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: bug

#928 Impl [Nuclio] Use DNS-1035 for function names instead of DNS-1123
  src/i18n/en/common.json
  src/igz_controls/services/validating-patterns.service.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
Labels: enhancement

#927 [Nuclio] Function list: make checkboxes always visible
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/functions.component.js
  src/nuclio/functions/functions.tpl.html
Labels: enhancement

#929 Create a new dist version 0.17.0
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#930 Cleanup [General] Remove debugger directive
  src/nuclio/functions/functions.component.js
Labels: Cleanup

#931 Create a new dist version 0.17.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup

#933 [Projects][API GWs] Name: Change validation to DNS-1035
  src/i18n/en/functions.json
  src/nuclio/common/less/dialogs.less
Labels: Cleanup, enhancement

#932 [Nuclio] Resources: Add Inactivity Window field
  src/i18n/en/common.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#934 Create a new dist version 0.17.2
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#935 Fix [Nuclio] Configuration: Resources: pane is broken
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
Labels: bug

#936 Create a new dist version 0.17.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#940 Impl [Nuclio] Resources: add descriptions and tooltips
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#938 [Nuclio] Navigating directly to create function is broken
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/screens/create-function/create-function.component.js
Labels: bug

#939 [Nuclio] Configuration: Labels: Max length for key: 256
  src/nuclio/common/services/version-helper.service.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: enhancement

#937 [i18n] Add "N/A" to common namespace
  src/i18n/en/common.json
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
Labels: Cleanup

#941 Create a new dist version 0.17.4
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement

#942 [Nuclio] Confirm deletion/disabling when used by API-GW
  src/i18n/en/functions.json
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#943 Impl [Nuclio] Configuration: Labels: Max length for key: 250
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
Labels: enhancement

#944 Create a new dist version 0.17.5
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#945 Impl [General] Upgrade "karma" package
  package.json
Labels: dependencies

#946 Impl [General] Upgrade ESLint to v6
  .eslintignore
  .eslintrc.json
  package.json
  src/igz_controls/components/search-input/search-helper.service.js
  src/igz_controls/components/search-input/search-input.component.js
  src/igz_controls/components/size/size.component.js
  src/igz_controls/directives/multiline-ellipsis.directive.js
  src/igz_controls/services/form-validation.service.js
  src/igz_controls/services/prevent-dropdown-cut-off.service.js
  src/igz_controls/services/validating-patterns.service.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/common/components/navigation-tabs/navigation-tabs.service.js
  src/nuclio/common/services/export.service.js
  src/nuclio/functions/functions.component.js
Labels: Cleanup, dependencies

#947 Impl [General] Upgrade AngularJS to v1.7.9 and more packages
  package.json
Labels: dependencies

#948 Create a new dist version 0.18.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, dependencies

#949 Impl [Nuclio] V3IO Stream trigger: Remove Availability Timeout
  src/nuclio/functions/functions.service.js
Labels: enhancement

#950 Create a new dist version 0.18.1
  dist/js/iguazio.dashboard-controls.js
  package.json
Labels: enhancement

#951 [Nuclio] Indicate whether function is used by an API-GW
  src/i18n/en/functions.json
  src/igz_controls/fonts/iguazio.eot
  src/igz_controls/fonts/iguazio.json
  src/igz_controls/fonts/iguazio.svg
  src/igz_controls/fonts/iguazio.ttf
  src/igz_controls/fonts/iguazio.woff
  src/igz_controls/less/icons.less
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.less
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
Labels: enhancement

#952 Fix [Nuclio] Triggers: cannot scroll down, content unreachable
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: bug

#953 Fix [Nuclio] Triggers: headers not frozen when scrolling
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
Labels: bug

#954 Impl [Nuclio] Triggers: Worker Availability Timeout: no zero
  src/i18n/en/functions.json
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#955 Create a new dist version 0.18.2
  dist/fonts/iguazio.eot
  dist/fonts/iguazio.json
  dist/fonts/iguazio.svg
  dist/fonts/iguazio.ttf
  dist/fonts/iguazio.woff
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#957 Fix [Nuclio] Configuration:Resources:Target CPU: Value not set
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
Labels: bug

#958 Create a new dist version 0.18.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#956 [Nuclio] Clicking on deploy not applying changes
  src/i18n/en/functions.json
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
  src/nuclio/functions/version/version.component.js
  src/nuclio/functions/version/version.tpl.html
Labels: bug

#959 Create a new dist version 0.18.4
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug
