Repository iguazio/dashboard-controls, pull requests merged in 2020-07, with the labels that each got.

#1035 Fix [Nuclio] Resources: CPU Request: No warning on clearing field
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
Labels: bug

#1036 Fix [Nuclio] Functions: deleted function not removed from list
  src/nuclio/functions/functions.component.js
Labels: bug

#1037 Create a new dist version 0.23.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1038 Impl [Nuclio] Triggers: Consumer Group Name: set maxlegnth to 256
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1039 Fix [Nuclio] V3IO-stream trigger: Access Key populated improperly
  src/nuclio/functions/functions.service.js
Labels: bug

#1040 Create a new dist version 0.23.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1041 Impl [Nuclio] Resources: CPU: Remove warning icon + message
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#1042 Create a new dist version 0.23.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1043 Impl [TableService] Add communication-events table-column widths
  src/igz_controls/services/table-size.service.js
Labels: enhancement

#1044 Create a new dist version 0.23.5
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1045 [API Gateway][Browse] Bottom Edge Scroll Slider defect
  build.config.js
  gulpfile.js
  src/igz_controls/images/mCSB_buttons.png
  src/third-party/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js
  src/third-party/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.less
  src/third-party/ng-scrollbars/scrollbars.min.js
Labels: bug

#1046 Create a new dist version 0.23.6
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1047 Fix [Build] vendor file missing in distribution folder
  .gitignore
  build.config.js
Labels: bug

#1048 Create a new dist version 0.23.7
  dist/js/iguazio.dashboard-controls.js
  dist/js/vendor.js
  dist/less/iguazio.dashboard-controls.less
  dist/less/vendor.less
  package.json
Labels: bug

#1049 [Functions] Auto-refresh every 5 seconds
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/functions.component.js
Labels: enhancement

#1050 Create a new dist version 0.23.8
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1051 Impl [Nuclio] Triggers: Kafka: Brokers & Topics: no empty lists
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
Labels: enhancement

#1052 Create a new dist version 0.23.9
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1053 Impl [Validation] Split service resources to config/catalog
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1054 Create a new dist version 0.23.10
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1056 Impl [Build] Upgrade "gulp-uglify" package to ^3.0.2
  package.json
Labels: dependencies, enhancement

#1057 Create a new dist version 0.23.11
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: dependencies, enhancement

#1059 Impl [Nuclio] Resources: more-info tooltip: allocated->reserved
  src/i18n/en/common.json
Labels: enhancement

#1060 Create a new dist version 0.23.12
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
