Repository iguazio/dashboard-controls, pull requests merged in 2020-04, with the labels that each got.

#960 [Nuclio] Delete function dialog: Wrong style and button
  src/i18n/en/functions.json
  src/nuclio/functions/functions.component.js
Labels: bug

#961 Create a new dist version 0.18.5
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#962 Impl [Nuclio] Delete function dialog: Wrong style and button
  src/i18n/en/functions.json
  src/nuclio/functions/functions.component.js
Labels: bug

#963 Create a new dist version
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#965 [Users] Groups: add Apply/Cancel buttons
  src/igz_controls/services/prevent-dropdown-cut-off.service.js
Labels: bug

#966 [Nuclio] Reduce max length of function name to 56
  src/igz_controls/services/validating-patterns.service.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
Labels: enhancement

#964 [Nuclio] Display system default values of some fields
  src/i18n/en/functions.json
  src/igz_controls/components/more-info/more-info.component.js
  src/igz_controls/components/more-info/more-info.less
  src/igz_controls/components/more-info/more-info.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#967 [Nuclio] Import: skip/override functions with same name
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/igz_controls/components/import-project-dialog/import-project-dialog.component.js
  src/igz_controls/components/import-project-dialog/import-project-dialog.tpl.html
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.component.js
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.component.spec.js
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.less
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.tpl.html
Labels: enhancement

#968 Create a new dist version 0.19.0
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#969 [Users] Add password validation rules for password strength
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: enhancement

#970 Create a new dist version 0.19.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#971 Move "Inactivity window" field out of demo mode
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#972 Impl [igzValidatingInputField] Refactor component to use ngModel
  src/igz_controls/components/action-menu/action-menu.component.js
  src/igz_controls/components/info-page/info-page-content/info-page-content.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
  src/igz_controls/services/dialogs.service.js
  src/igz_controls/services/form-validation.service.js
  src/igz_controls/services/validating-patterns.service.js
  src/igz_controls/services/window-dimensions.service.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/common/less/general-rules.less
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template-dialog/function-from-template-dialog.tpl.html
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.tpl.html
  src/nuclio/functions/version/function-event-dialog/function-event-dialog.component.js
  src/nuclio/functions/version/function-event-dialog/function-event-dialog.tpl.html
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
  src/nuclio/functions/version/version-code/version-code.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build-dialog/version-configuration-build-dialog.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-runtime-attributes/version-configuration-runtime-attributes.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.component.js
Labels: Cleanup, bug, enhancement

#973 Impl [Nuclio] Test pane: do not hide border of Path field
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.less
Labels: enhancement

#974 Impl [igzValidatingInputField] Add `borders-mode` attribute
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.less
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: enhancement

#975 Create a new dist version 0.20.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#976 Fix [igzValidatingInputField] Fix various bugs from reent refactor
  src/igz_controls/components/validating-input-field/validating-input-field.component.js
  src/igz_controls/components/validating-input-field/validating-input-field.component.spec.js
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: Cleanup, bug, enhancement

#977 Create a new dist version 0.20.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, bug, enhancement
