Repository iguazio/dashboard-controls, pull requests merged in 2021-03, with the labels that each got.

#1219 Cleanup [igzAutoComplete] Fix doc comments
  src/igz_controls/components/auto-complete/auto-complete.component.js
Labels: Cleanup

#1220 [Alerts] Add option to filter by description using RegEx
  src/igz_controls/components/info-page/info-page-filters/info-page-filters.less
Labels: enhancement

#1221 Create a new dist version 0.33.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup, enhancement

#1222 Impl [Validation] Accommodate to new tenant name rules
  src/igz_controls/services/validation.service.js
Labels: enhancement

#1223 Impl [Nuclio] Entirely deprecate project disply name
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
  src/nuclio/common/screens/create-function/create-function.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/common/screens/create-function/function-import/function-import.component.js
  src/nuclio/common/services/export.service.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.spec.js
Labels: enhancement

#1224 Create a new dist version 0.34.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1225 [Nuclio] Function>Code: add Git option to Code Entry Type
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-code/version-code.component.js
  src/nuclio/functions/version/version-code/version-code.tpl.html
Labels: enhancement

#1227 Impl [Build] Upgrade packages to remedy vulnerabilities
  package.json
Labels: dependencies

#1228 Create a new dist version 0.34.1
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: dependencies, enhancement
