Repository iguazio/dashboard-controls, pull requests merged in 2021-07, with the labels that each got.

#1255 Fix [Nuclio] Triggers: Cron trigger schedule unexpectedly changed
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: enhancement

#1256 Create a new dist version 0.36.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1257 Fix [Nuclio] Triggers: Cron trigger schedule unexpectedly changed
  src/nuclio/functions/version/version-triggers/version-triggers.component.js
Labels: bug

#1258 Create a new dist version v0.31.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1259 [Nuclio] Functions: add pagination on frontend
  src/igz_controls/components/action-checkbox-all/action-checkbox-all.component.js
  src/igz_controls/components/action-checkbox-all/action-checkbox-all.tpl.html
  src/igz_controls/less/custom-dropdown.less
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.tpl.html
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.component.js
  src/nuclio/functions/functions.component.spec.js
  src/nuclio/functions/functions.less
  src/nuclio/functions/functions.tpl.html
Labels: enhancement

#1260 [Nuclio] Test pane: Invocation URLs not updated after deploy
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: bug

#1261 Create a new dist version 0.36.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
