Repository iguazio/dashboard-controls, pull requests merged in 2021-02, with the labels that each got.

#1205 Impl [Nuclio] Remove runtime Python 2.7 and add 3.7 and 3.8
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.js
  src/nuclio/common/screens/create-function/function-from-scratch/function-from-scratch.component.spec.js
  src/nuclio/common/screens/create-function/function-from-template/function-from-template.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/version/version-code/version-code.component.js
Labels: enhancement

#1206 Create a new dist version 0.32.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1207 [Nuclio] Breadcrumbs dropdown: make wider and add tooltip
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.less
  src/nuclio/common/components/breadcrumbs-dropdown/breadcrumbs-dropdown.tpl.html
Labels: enhancement

#1208 [Storage Pool] Input rules length and input length counter mismatch
  src/igz_controls/services/validation.service.js
Labels: bug

#1209 Impl [Nucio] Function volumes: Bring back Host Path kind
  src/i18n/en/functions.json
  src/nuclio/common/components/collapsing-row/collapsing-row.less
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.component.js
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
Labels: enhancement

#1210 Impl [Nuclio] Click project breadcrumb to go to Project screen
  src/nuclio/common/components/breadcrumbs/breadcrumbs.component.js
  src/nuclio/common/components/breadcrumbs/breadcrumbs.tpl.html
Labels: enhancement

#1211 Create a new dist version 0.33.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1212 Impl [Nuclio] Volumes: remove red asterisk from Read Only field
  src/nuclio/common/components/edit-item/edit-item.tpl.html
Labels: enhancement

#1213 Create a new dist version 0.33.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1215 Fix [igzValidatingInputField] Hide clear on disabled/read-only
  src/igz_controls/components/validating-input-field/validating-input-field.tpl.html
Labels: bug, enhancement

#1216 Create a new dist version 0.33.2
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1217 [Services] Last service copy-to-clipboard menu is hidden
  src/igz_controls/components/action-menu/action-menu.component.js
  src/igz_controls/components/action-menu/action-menu.less
  src/nuclio/common/components/collapsing-row/collapsing-row.component.js
  src/nuclio/common/components/collapsing-row/collapsing-row.tpl.html
  src/nuclio/common/components/edit-item/edit-item.tpl.html
  src/nuclio/common/components/key-value-input/key-value-input.component.js
  src/nuclio/common/components/key-value-input/key-value-input.tpl.html
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-annotations/version-configuration-annotations.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-environment-variables/version-configuration-environment-variables.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-labels/version-configuration-labels.tpl.html
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-volumes/version-configuration-volumes.tpl.html
Labels: enhancement

#1218 Create a new dist version 0.33.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
