Repository iguazio/dashboard-controls, pull requests merged in 2021-06, with the labels that each got.

#1231 [Nuclio] Functions: Add Owner column
  src/igz_controls/services/table-size.service.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/functions/functions.component.js
  src/nuclio/functions/functions.less
  src/nuclio/functions/functions.tpl.html
Labels: enhancement

#1232 [Nuclio] Resources: Add Node Selectors
  src/i18n/en/functions.json
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#1233 Impl [Nuclio] List internal/external invocation URLs
  src/i18n/en/functions.json
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.tpl.html
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.component.js
  src/nuclio/functions/function-collapsing-row/function-version-row/function-version-row.tpl.html
  src/nuclio/functions/functions.service.js
  src/nuclio/functions/functions.tpl.html
  src/nuclio/functions/version/version-monitoring/version-monitoring.component.js
  src/nuclio/functions/version/version-monitoring/version-monitoring.less
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
  src/nuclio/functions/version/version-triggers/version-triggers.tpl.html
  src/nuclio/functions/version/version.component.js
Labels: enhancement

#1234 Create a new dist version 0.35.0
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1235 Impl [Nuclio] Resources: Add Node Selectors
  src/i18n/en/functions.json
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#1236 Create a new dist version
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1237 Impl [Nuclio] Resources: Add Node Selectors
  src/i18n/en/functions.json
  src/nuclio/common/components/key-value-input/key-value-input.less
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.component.js
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#1238 Create a new dist version
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1239 Impl [Nuclio] Move Node Selectors and rename
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#1240 Impl [Nuclio] Accommodate to internal/externalInvocationUrls
  src/nuclio/functions/version/version-monitoring/version-monitoring.tpl.html
Labels: enhancement

#1241 Create a new dist version 0.35.1
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1242 Impl [Nuclio] Move Node Selectors and rename
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: enhancement

#1243 Create a new dist version v0.31.3
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1244 Clean [i18n] Rename key message of "Create a new entry"
  src/i18n/en/common.json
  src/i18n/en/functions.json
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-resources/version-configuration-resources.tpl.html
Labels: Cleanup

#1245 Create a new dist version 0.35.2
  dist/i18n/en/common.json
  dist/i18n/en/functions.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: Cleanup

#1246 Impl [Nuclio] Triggers: add Tech Preview note for a few classes
  src/i18n/en/common.json
  src/nuclio/functions/functions.service.js
Labels: enhancement

#1247 Create a new dist version 0.35.3
  dist/i18n/en/common.json
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1248 Fix [Nuclio] Functions: table overflows viewport
  src/igz_controls/services/table-size.service.js
  src/nuclio/functions/functions.less
Labels: bug

#1249 Create a new dist version 0.35.4
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug

#1252 Create a new dist version 0.36.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement

#1253 Impl [Nuclio] Test pane: add project name on saving events
  src/nuclio/functions/version/version-code/function-event-pane/function-event-pane.component.js
Labels: enhancement

#1254 Create a new dist version 0.36.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: enhancement
