Repository iguazio/dashboard-controls, pull requests merged in 2021-01, with the labels that each got.

#1185 [Projects] Allow to forcefully delete a non-empty project
  src/i18n/en/functions.json
Labels: enhancement

#1186 Impl [i18n] Add "Not ready" message
  src/i18n/en/common.json
  src/igz_controls/services/local-storage.service.js
Labels: enhancement

#1188 Impl [igzMultipleCheckboxes] Unit tests: cleanup DOM element
  src/igz_controls/components/multiple-checkboxes/multiple-checkboxes.component.spec.js
Labels: enhancement

#1189 Fix [Nuclio] Actions remain disabled on deploy immediate error
  src/nuclio/functions/version/version.component.js
Labels: bug

#1190 Impl [Nuclio] Omit readiness timeout from request on empty field
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-build/version-configuration-build.component.js
Labels: enhancement

#1191 Create a new dist version 0.30.3
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1193 Impl [Nuclio] Function: add unique classname to stale version msg
  src/nuclio/functions/functions.service.js
Labels: enhancement

#1194 Fix [Nuclio] Functions: broken enabling/disabling messages
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
Labels: bug

#1195 Fix [Nuclio] Functions: start/stop: resource version not updating
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
Labels: bug

#1196 Fix [Nuclio] Function: missing error on disabling with API GW
  src/nuclio/functions/duplicate-function-dialog/duplicate-function-dialog.component.js
  src/nuclio/functions/function-collapsing-row/function-collapsing-row.component.js
  src/nuclio/functions/functions.tpl.html
  src/nuclio/functions/version/version.component.js
Labels: bug

#1197 Fix [Nuclio] Function: Falsely displays error on disabling
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
Labels: bug

#1198 Fix [Nuclio] Function: missing error on disabling with API GW
  src/nuclio/functions/version/version-configuration/tabs/version-configuration-basic-settings/version-configuration-basic-settings.component.js
Labels: bug

#1199 Impl [Nuclio] Function: add indication for API gateway + name
  src/nuclio/functions/version/version.less
  src/nuclio/functions/version/version.tpl.html
Labels: enhancement

#1200 Create a new dist version 0.31.0
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement

#1201 [Browse] Table cell width is broken on window expanding
  src/igz_controls/directives/resizable-table-column.directive.js
Labels: bug

#1202 Impl [API GWs] Use consistent function status for display
  src/nuclio/api-gateways/new-api-gateway-wizard/new-api-gateway-wizard.component.js
Labels: enhancement

#1203 Fix [API GWs] Transient status is displayed instead of loader
  src/nuclio/api-gateways/api-gateways.component.js
Labels: bug

#1204 Create a new dist version 0.31.1
  dist/js/iguazio.dashboard-controls.js
  dist/less/iguazio.dashboard-controls.less
  package.json
Labels: bug, enhancement
